export default [
  {
    slug: "what-is-ai-seo",
    title: "What Is AI SEO? How to Get Your Business Recommended by ChatGPT, Gemini and Google",
    metaDescription: "More homeowners now ask AI assistants who to hire. AI SEO is how you make sure your business is in the answer. What it is, how it works and what you can do today.",
    excerpt: "More people now ask ChatGPT, Gemini or Google's AI who to hire before they ever scroll through search results. AI SEO is how you make sure your business is in the answer.",
    category: "AI Search",
    keywords: ["AI SEO", "generative engine optimization", "ChatGPT recommendations", "AI search visibility"],
    content: [
      "A homeowner in Richmond Hill notices water stains on the ceiling. A few years ago, she would have typed 'roofer near me' into Google and scrolled through results. Today, she might open ChatGPT and ask, 'Who's a reliable roofer in Richmond Hill for a leak repair?' Or she searches Google and reads the AI Overview at the top before looking at anything else.",
      "Either way, the AI gives her a short answer that names a few businesses. If yours isn't one of them, you may never get the chance to compete. AI SEO is the work of making sure you are.",
      "## What AI SEO actually means",
      "AI SEO, sometimes called generative engine optimization (GEO), is the practice of making your business easy for AI assistants to find, understand, trust and recommend. That includes ChatGPT, Google Gemini, Google's AI Overviews and AI Mode, Microsoft Copilot and Perplexity.",
      "It builds on traditional SEO rather than replacing it. Many AI tools pull from search indexes, map data, review sites and directories to form their answers, so solid SEO basics are still the foundation. What changes is the emphasis: AI tools reward businesses whose information is consistent everywhere, whose content answers questions directly, and who are clearly vouched for by other sources. We compare the two in detail in [AI SEO vs traditional SEO](/blog/ai-seo-vs-traditional-seo).",
      "![A homeowner in a kitchen asking an AI assistant on her phone to recommend a local roofer](/blog/img/what-is-ai-seo-1.webp \"More homeowners now ask an AI assistant who to hire before they search.\")",
      "## How AI assistants decide who to recommend",
      "No AI company publishes its exact recipe, and each tool works a little differently. But the businesses that get mentioned tend to share a few traits:",
      "- **They're easy to identify.** The business name, address, phone, services and service area match across the website, Google Business Profile and directories.",
      "- **Other sources talk about them.** Reviews, local news, associations, suppliers and community sites confirm the business is real and respected.",
      "- **Their content answers real questions.** Clear, specific pages are easy for AI to quote.",
      "- **Their reviews mention specifics.** Reviews that name the service, the city and the result help AI match a business to a request.",
      "- **Their website is technically readable.** Fast pages, clean HTML and structured data make the information easy to process.",
      "We go deeper on this in [how AI assistants choose which businesses to recommend](/blog/how-ai-assistants-choose-businesses).",
      "## What AI SEO work includes",
      "### 1. Make your business information consistent everywhere",
      "Start with your Google Business Profile, then make sure the same name, phone, website and service area appear on Bing Places, Apple Business Connect, Yelp and the directories that matter in your trade. For GTA home services, that often includes HomeStars and Houzz. Microsoft's Bing data feeds several AI tools, and Apple's data powers Siri and Apple Maps, so these listings matter more than many businesses realize. Our [Google Business Profile guide](/blog/google-business-profile-optimization) is a good place to start.",
      "### 2. Write content that answers questions directly",
      "AI assistants build answers from passages that clearly respond to a question. A sentence like 'We repair and replace asphalt shingle roofs across Richmond Hill, Vaughan and Aurora, and most leak repairs are done within two days of the inspection' is far more useful to an AI than 'We pride ourselves on quality craftsmanship.'",
      "Give each service its own page. Answer the questions customers ask on every estimate. Add a short FAQ section to key pages, written in plain language.",
      "### 3. Add structured data",
      "Structured data, or schema markup, is code that labels your information for machines: this is a local business, these are its services, this is its service area, these are frequently asked questions. It removes guesswork for both search engines and AI tools. See [schema markup explained](/blog/schema-markup-explained).",
      "### 4. Let AI crawlers read your site",
      "Some websites accidentally block the crawlers AI tools use to find content. Check that your robots.txt file isn't blocking search crawlers such as Googlebot, Bingbot, OAI-SearchBot (used for ChatGPT search) or PerplexityBot. Some sites also publish an llms.txt file, a newer and still-evolving convention for summarizing a site for AI tools. Read more in [what is llms.txt](/blog/what-is-llms-txt).",
      "### 5. Earn reviews and mentions",
      "Reviews are some of the strongest evidence an AI can find, especially detailed ones. Beyond reviews, look for real-world mentions: membership in a trade association such as HRAI for HVAC contractors, RenoMark for renovators, your local chamber of commerce, manufacturer dealer listings, sponsorships, and local news coverage. Each one is another independent source saying you exist and do good work. See [why Google reviews matter in the age of AI search](/blog/google-reviews-and-ai-search).",
      "## How to measure AI visibility",
      "Unlike classic search rankings, there's no single position to track. The practical approach is to regularly ask the main assistants the questions your customers ask, such as 'best furnace repair in Vaughan' or 'who installs heat pumps in Markham', and record whether you're mentioned, how you're described, and which sources are cited. Over time, you can see whether your visibility is improving and which competitors keep showing up.",
      "![A business owner reviewing a report of AI search mentions on a laptop in a small office](/blog/img/what-is-ai-seo-2.webp \"Track where you're mentioned across AI assistants, and which competitors show up instead.\")",
      "## What AI SEO can't do",
      "Be wary of anyone who guarantees you'll be the top recommendation in ChatGPT. Nobody controls how these tools rank businesses, and their answers vary from person to person and day to day. What you can control is how clear, consistent and well supported your business information is. That consistently improves your odds.",
      "It also takes time. AI tools update their understanding of a business gradually as new reviews, mentions and content appear. Expect steady progress over months, not overnight results.",
      "## Where to start",
      "If you do only three things this month, make them these:",
      "- Fully complete and verify your Google Business Profile, Bing Places and Apple Business Connect listings with identical details.",
      "- Make sure your website has a clear page for each main service that answers common questions directly.",
      "- Start asking every customer for a Google review.",
      "## The bottom line",
      "AI assistants are quickly becoming the first place homeowners go for recommendations. The businesses they name are the ones that are easy to understand, consistent everywhere, and clearly trusted by others. That's what AI SEO builds.",
      "AI search optimization is included in our Growth and Authority plans, and we track where you're mentioned every month. Curious where you stand today? [Request a free AI visibility audit](/contact?interest=audit).",
    ],
  },
  {
    slug: "how-ai-assistants-choose-businesses",
    title: "How ChatGPT, Gemini and Perplexity Decide Which Businesses to Recommend",
    metaDescription: "When a homeowner asks an AI assistant who to hire, how does it pick? What AI tools look for in a local business, and what contractors can do to be the one they name.",
    excerpt: "AI assistants can't call around or visit your shop. They rely on what they can read about you online. Here's what they look for.",
    category: "AI Search",
    keywords: ["AI recommendations", "ChatGPT local business", "Perplexity SEO", "Gemini search"],
    content: [
      "Ask ChatGPT 'Who's a good plumber in Vaughan for a sump pump install?' and you'll usually get a short answer naming two to five businesses, often with a sentence about each. Ask Perplexity or Gemini and you'll get something similar, sometimes with links to where the information came from.",
      "Those few names get a huge share of attention. So how does an AI assistant decide who makes the list? It can't drive past your shop, call your office or look at your work. It relies entirely on what it can read about you online. That's good news, because most of what it reads is something you can influence.",
      "## Where AI assistants get their information",
      "Each tool works a little differently, and none publishes its exact method, but they draw on the same kinds of sources:",
      "- **Search indexes.** When an assistant searches the web to answer a question, it pulls from search engines' indexes of web pages, including your website.",
      "- **Map and business listings.** Google Business Profile, Bing Places, Apple Business Connect and similar listings hold your name, category, hours, location and reviews.",
      "- **Review sites and directories.** Google reviews, Yelp, HomeStars, Houzz, the BBB and trade directories.",
      "- **Other websites that mention you.** Local news, association member lists, supplier dealer locators, community sites and blogs.",
      "- **Training data.** The general knowledge a model learned before its cutoff date. This matters less for local businesses, because it's often out of date.",
      "![A homeowner on a porch asking an AI assistant on her phone to recommend a local plumber](/blog/img/how-ai-assistants-choose-businesses-1.webp \"AI assistants build their answers from what they can find and verify about you online.\")",
      "## The five traits recommended businesses share",
      "### 1. They're easy to identify",
      "An AI assistant needs to be confident about who you are before it recommends you. If your business name, phone number, address or service area differs between your website, Google, Yelp and Facebook, it can't be sure those listings are the same business. Doubt usually means you get left out.",
      "Pick one exact version of your business name, phone number and service area, and use it everywhere. That includes small details, like 'Northline Plumbing Inc.' versus 'Northline Plumbing & Drains'.",
      "### 2. Other sources vouch for them",
      "Your own website saying you're the best plumber in Vaughan carries limited weight. Independent sources saying good things about you carry much more. Reviews, a mention in a local news story, a listing on a manufacturer's dealer page, membership in a trade association or a sponsorship of a local team all count as outside confirmation that you're real and respected.",
      "### 3. Their content answers questions directly",
      "Assistants build answers from passages that clearly respond to a question. Compare these two sentences:",
      "- 'We pride ourselves on excellence and customer satisfaction.'",
      "- 'We install sump pumps and backwater valves across Vaughan, Woodbridge and Maple, and most installs are completed in a single day.'",
      "The second tells an AI exactly what you do, where, and how quickly. It's quotable. The first says nothing it can use. Service pages and FAQs written in this direct style give assistants material to work with.",
      "### 4. Their reviews say specific things",
      "Star ratings and review counts matter, but so does what reviewers write. A review that says 'They installed our new sump pump in Woodbridge the same day our old one failed' connects your business to a service, a place and an outcome. Hundreds of reviews like that make it easy for an assistant to match you to a specific request. Our post on [Google reviews in the age of AI search](/blog/google-reviews-and-ai-search) covers how to earn them.",
      "### 5. Their website is technically readable",
      "If your key information is buried in images, hidden behind scripts that crawlers struggle with, or on pages that load slowly, AI tools may never see it. A fast site with clean HTML, clear headings and structured data makes your information easy to process. It also matters that your site doesn't accidentally block the crawlers AI tools use. See [technical SEO basics](/blog/technical-seo-basics).",
      "## How each assistant differs",
      "The details shift often, but a few broad patterns are worth knowing:",
      "- **Google's AI Overviews and AI Mode** draw on Google's own search index and Business Profile data, so your Google presence matters most here. See [Google AI Overviews explained](/blog/google-ai-overviews-explained).",
      "- **ChatGPT** can search the web when answering questions about local businesses, and its results lean on third-party search data and the sites it can crawl.",
      "- **Perplexity** searches the web for almost every answer and usually shows its sources, which makes it a useful way to see which sites are shaping what AI says about you.",
      "- **Microsoft Copilot** is built on Bing, so a complete Bing Places listing helps.",
      "Because they draw from different places, being consistent everywhere matters more than optimizing for any single tool.",
      "![A contractor reviewing his business listings on a laptop and phone at a kitchen table](/blog/img/how-ai-assistants-choose-businesses-2.webp \"Consistent listings across Google, Bing, Apple and directories help every assistant recognize you.\")",
      "## What this looks like for a real contractor",
      "Picture two electricians in Markham with similar skills. The first has a Google profile with 18 reviews, a website with one 'Services' page, an old phone number on Yelp, and no mentions anywhere else. The second has 160 detailed reviews, a page for each service, consistent listings on Google, Bing, Apple, HomeStars and the BBB, an ESA licence number on the site, and a mention on a local builder's preferred trades page.",
      "Ask an AI assistant for an electrician in Markham and the second one is far more likely to come up. Not because of a trick, but because there's simply much more trustworthy, consistent evidence about them.",
      "## What you can't control",
      "Nobody can guarantee a spot in an AI's answer. Results vary between users, change over time, and depend on exactly how a question is phrased. Be cautious of anyone promising guaranteed AI placement. What you can do is stack the odds in your favour by making your business clear, consistent and well supported across the web.",
      "## A simple starting checklist",
      "- Make your name, phone number and service area identical everywhere.",
      "- Complete your Google Business Profile, Bing Places and Apple Business Connect listings.",
      "- Give each main service its own page with direct, specific answers.",
      "- Ask every customer for a review, and encourage them to mention the job and the city.",
      "- Look for real local mentions: associations, suppliers, sponsorships, local news.",
      "- Check that your website loads quickly and isn't blocking search crawlers.",
      "## The bottom line",
      "AI assistants recommend businesses they can understand and trust. They learn both from what's written about you across the web. The more consistent, specific and independently confirmed that information is, the more often you'll be named.",
      "This is the core of the AI search work in our Growth and Authority plans. Want to see what AI assistants say about your business right now? [Request a free AI visibility audit](/contact?interest=audit). For the bigger picture, start with [what AI SEO is](/blog/what-is-ai-seo).",
    ],
  },
  {
    slug: "google-ai-overviews-explained",
    title: "Google AI Overviews Explained: What They Mean for Contractors' Website Traffic",
    metaDescription: "Google now answers many searches with an AI summary above the regular results. What AI Overviews are, how they affect clicks for local businesses, and how to show up in them.",
    excerpt: "Google now answers many searches with an AI summary at the top of the page. Here's what that means for your traffic and how to adapt.",
    category: "AI Search",
    keywords: ["Google AI Overviews", "AI Mode", "zero-click search", "SEO for contractors"],
    content: [
      "Search Google for 'why is my furnace short cycling' and you'll often see a block of AI-written text at the very top of the page, above the ads and the regular results. That's an AI Overview. It summarizes an answer from several websites and shows small links to some of the sources.",
      "For homeowners, it's convenient. For contractors who rely on Google for leads, it raises a fair question: if Google answers the question itself, will anyone still click through to your website? The answer is more nuanced than the headlines suggest.",
      "## What AI Overviews are",
      "AI Overviews are summaries generated by Google's Gemini models. They appear for some searches, usually questions or searches where Google thinks a quick summary will help. They pull information from pages in Google's index and link to some of those pages as sources.",
      "Google has also introduced AI Mode, a more conversational search experience where people can ask follow-up questions. Both draw on the same idea: Google uses AI to combine information from many pages into one answer.",
      "Importantly, Google says there are no special technical requirements to appear in AI Overviews. Pages are eligible if they're indexed and eligible to appear in normal search with a snippet. The same fundamentals that help you rank also help you get cited.",
      "![A homeowner reading an AI-generated answer at the top of a search results page on a laptop](/blog/img/google-ai-overviews-explained-1.webp \"AI Overviews summarize an answer at the top of the page, with links to some sources.\")",
      "## How they affect your traffic",
      "### Informational searches get fewer clicks",
      "Searches for general information, like 'what size furnace do I need' or 'how long does a roof last', are the ones most likely to show an AI Overview. Some people get what they need from the summary and never click. If a big share of your website traffic came from those kinds of how-to questions, you may see fewer visits.",
      "### Searches to hire someone behave differently",
      "Searches like 'furnace repair Vaughan', 'emergency plumber near me' or 'roofer Brampton' are different. People searching these want to hire someone, and Google typically shows the map results with local businesses prominently. These searches are where most contractor leads come from, and they're far less likely to be fully answered by a summary.",
      "### The clicks you do get can be better",
      "A homeowner who reads an overview and then clicks your link has already learned the basics. They often arrive closer to making a decision. Fewer, better-qualified visitors can be a fair trade if they turn into calls.",
      "## How to show up in AI Overviews",
      "Because AI Overviews draw from Google's normal index, the work overlaps heavily with good SEO. A few things help in particular.",
      "### Answer real questions clearly",
      "Write pages and posts that answer the questions homeowners actually ask, near the top of the page and in plain language. 'Short cycling usually means the furnace is overheating, the flame sensor is dirty, or the thermostat is in the wrong spot' is the kind of direct answer an overview can cite.",
      "### Show real experience",
      "Google's guidance emphasizes helpful, people-first content that shows experience and expertise. A contractor explaining what they see on real jobs in GTA homes, with real photos, has something a generic article doesn't. Lean into that.",
      "### Cover the follow-up questions",
      "Overviews often address several related questions at once. A page that covers the main question and the natural follow-ups, like cost factors, how long the work takes and when to call a professional, gives Google more to draw from.",
      "### Keep your site technically healthy",
      "Pages need to be indexed to be cited. Fast loading, clean structure, sensible headings and structured data all help. See [technical SEO basics](/blog/technical-seo-basics) and [schema markup explained](/blog/schema-markup-explained).",
      "### Build your Business Profile and reviews",
      "For local searches, Google leans on Business Profile information and reviews. A complete, active profile with lots of specific reviews is still one of the strongest local signals. Our [Google Business Profile guide](/blog/google-business-profile-optimization) walks through it.",
      "## Rethink what you measure",
      "If informational traffic drops but calls and booked jobs hold steady or rise, your marketing is still working. Traffic was always a means to an end. Track:",
      "- Calls and form submissions from search.",
      "- Calls, clicks and direction requests from your Business Profile.",
      "- Booked estimates and won jobs by source.",
      "- Whether you're cited in AI Overviews for your most important questions.",
      "![A contractor reviewing a simple dashboard of calls and booked jobs on a laptop in his office](/blog/img/google-ai-overviews-explained-2.webp \"Calls and booked jobs matter more than raw website traffic.\")",
      "## Should you still write blog posts?",
      "Yes, but write them differently. Generic posts that rehash common knowledge are exactly what AI summaries replace. Posts built on your real experience, local specifics and clear answers are more likely to be cited, and they build the trust that turns a reader into a customer. Our post on [how often a business should blog](/blog/how-often-should-a-business-blog) covers what's worth writing.",
      "## The bottom line",
      "AI Overviews change how people get quick answers, but they haven't changed how homeowners hire contractors. People still search for a business, compare reviews and call. Focus on being the business that's easy to find, easy to trust and easy to cite, and you'll do well in both the classic results and the AI summary above them.",
      "AI search optimization is part of our Growth and Authority plans. To learn how this fits the wider picture, read [what AI SEO is](/blog/what-is-ai-seo), or [request a free AI visibility audit](/contact?interest=audit).",
    ],
  },
  {
    slug: "schema-markup-explained",
    title: "Schema Markup Explained: The Hidden Code That Helps Google and AI Understand Your Business",
    metaDescription: "Schema markup labels your business details for search engines and AI tools. What it is, which types matter for contractors, what it can and can't do, and how to check it.",
    excerpt: "Schema markup is code that labels your business details so machines don't have to guess. Here's what contractors actually need.",
    category: "AI Search",
    keywords: ["schema markup", "structured data", "local business schema", "contractor SEO"],
    content: [
      "When a person reads your website, they understand instantly that '(416) 555-0123' is your phone number and 'Serving Etobicoke and Mississauga' describes where you work. Search engines and AI tools are good at figuring this out too, but they still have to guess. Schema markup removes the guesswork.",
      "Schema markup, also called structured data, is a small block of code added to your pages that labels your information in a standard format: this is a business, this is its name, this is its phone number, these are its services. You can't see it on the page, but search engines and AI tools can read it.",
      "## Why it matters more now",
      "Structured data has been around for over a decade, mainly to help Google show enhanced search results. It matters more today because AI assistants and Google's AI features are trying to understand businesses accurately enough to recommend them. Clear, machine-readable facts about who you are, what you do and where you work make that easier. For the wider context, see [how AI assistants choose which businesses to recommend](/blog/how-ai-assistants-choose-businesses).",
      "## The schema types that matter for contractors",
      "Schema.org, the shared vocabulary behind structured data, includes types designed specifically for trades. Using the most specific one helps.",
      "### LocalBusiness, using your trade's specific type",
      "This is the most important one. Rather than the generic LocalBusiness, use the specific type that fits, such as Plumber, Electrician, HVACBusiness, RoofingContractor, HousePainter or GeneralContractor. Include:",
      "- Your exact business name, matching your Google Business Profile.",
      "- Phone number and website.",
      "- Address, if customers visit you, or service area if you go to them.",
      "- Hours, including whether you offer emergency service.",
      "- Logo and a representative photo.",
      "- Links to your official profiles, like Google, Facebook and HomeStars, using the sameAs property.",
      "![A web developer adding structured data code to a contractor's website on a large monitor](/blog/img/schema-markup-explained-1.webp \"Structured data sits in your page's code, invisible to visitors but read by search engines and AI tools.\")",
      "### Service",
      "Service markup describes individual services, such as furnace installation or roof repair, and links them to your business and the area you serve. It's especially useful on dedicated service pages.",
      "### FAQPage",
      "FAQ markup labels questions and answers. Since 2023, Google only shows FAQ rich results for a small set of well-known government and health websites, so you won't get the expandable FAQ boxes in search results. It can still help machines understand your content, but don't add it expecting a visual boost.",
      "### Article or BlogPosting",
      "For blog posts, this labels the headline, author, publish date and image. It helps search engines understand who wrote the content and when, which supports trust in your expertise.",
      "### BreadcrumbList",
      "Breadcrumb markup describes where a page sits in your site's structure, like Home, then Services, then Furnace Repair. Google can show it in search results instead of a raw URL.",
      "## What schema can't do",
      "It's worth being clear about the limits, because structured data is sometimes oversold:",
      "- **It isn't a ranking shortcut.** Schema helps search engines understand your content. It doesn't make weak content rank.",
      "- **It doesn't guarantee rich results.** Google decides whether to show enhanced results, and it has scaled many of them back.",
      "- **Self-serving review stars don't show.** Google doesn't display review star snippets for businesses marking up reviews about themselves on their own site, so adding your own five-star rating in schema won't put stars in your search listing.",
      "- **It must match what's on the page.** Marking up information that isn't visible to visitors, or that's misleading, goes against Google's guidelines and can earn a manual action.",
      "## How to add it",
      "Structured data is usually added as JSON-LD, a small block of code in the page's HTML. How you add it depends on your website:",
      "- **WordPress:** SEO plugins such as Yoast, Rank Math or All in One SEO add basic schema automatically and let you fill in business details.",
      "- **Website builders:** Wix and Squarespace add some schema automatically, with limited control over details.",
      "- **Custom sites:** Your developer adds it directly to page templates. This gives the most control, including trade-specific types and service markup.",
      "## How to check it",
      "Two free tools tell you whether your markup is working:",
      "- **Google's Rich Results Test** shows which structured data Google can read on a page and flags errors.",
      "- **The Schema Markup Validator** at validator.schema.org checks markup against the full schema.org vocabulary.",
      "In Google Search Console, the Enhancements section also reports structured data issues across your whole site.",
      "![A contractor checking a structured data test report on a laptop beside a cup of coffee](/blog/img/schema-markup-explained-2.webp \"Free testing tools show what Google can read and flag any errors.\")",
      "## Common mistakes",
      "- Business details in schema that don't match your Google Business Profile.",
      "- Using generic LocalBusiness when a specific trade type exists.",
      "- Copying the same schema block onto every page without updating it.",
      "- Old plugins adding duplicate or conflicting markup.",
      "- Marking up content that isn't actually on the page.",
      "## The bottom line",
      "Schema markup is one of the simplest ways to make your business information unambiguous for Google and AI tools. It won't transform weak content, but on a solid site it removes guesswork, supports your local presence and gives AI assistants clean facts to work with.",
      "We add and maintain structured data as part of our Growth and Authority plans, and every website we build includes the basics. Related reading: [what is llms.txt](/blog/what-is-llms-txt) and [technical SEO basics](/blog/technical-seo-basics).",
    ],
  },
  {
    slug: "what-is-llms-txt",
    title: "What Is llms.txt, and Does Your Business Website Need One?",
    metaDescription: "llms.txt is a proposed file that summarizes your website for AI tools. What it is, what it isn't, whether AI companies use it, and whether it's worth adding to a contractor website.",
    excerpt: "llms.txt is a small file that gives AI tools a summary of your website. Here's what it does, what it doesn't, and whether it's worth your time.",
    category: "AI Search",
    keywords: ["llms.txt", "AI crawlers", "AI search optimization", "robots.txt"],
    content: [
      "If you've read anything about AI search lately, you may have come across llms.txt. Some marketers call it essential. Others say it does nothing. As usual, the truth is somewhere in between, and for most contractors it's a minor detail compared with the basics.",
      "Here's a plain explanation of what it is, what it isn't, and whether it's worth adding to your website.",
      "## What llms.txt is",
      "llms.txt is a plain text file placed at the root of a website, at an address like yoursite.com/llms.txt. It was proposed in 2024 as a simple way to give large language models, the AI systems behind tools like ChatGPT, a clean summary of a website and links to its most important pages.",
      "The idea is that websites are full of navigation menus, scripts and layout code that make it harder for AI tools to find the actual information. An llms.txt file cuts through that with a short, structured overview written in Markdown.",
      "A contractor's llms.txt might include:",
      "- The business name and a one-paragraph description.",
      "- Main services, each linking to its page.",
      "- Service area.",
      "- Links to pricing, about, contact and key guides.",
      "![A laptop on a clean desk displaying a simple text file outline of a business website](/blog/img/what-is-llms-txt-1.webp \"llms.txt is a short, plain summary of your site and its most important pages.\")",
      "## What llms.txt is not",
      "It's easy to confuse llms.txt with other files, so it's worth being precise:",
      "- **It isn't robots.txt.** Robots.txt tells crawlers which parts of your site they're allowed to access. llms.txt doesn't control access at all.",
      "- **It isn't a sitemap.** A sitemap lists every page so search engines can find them. llms.txt is a curated summary of the most important ones.",
      "- **It isn't an official standard.** It's a community proposal, not something adopted by a standards body.",
      "## Do AI companies actually use it?",
      "This is the important part. As of now, no major AI search provider has said that it relies on llms.txt to decide what to show or recommend, and Google has said publicly that it doesn't use it for search. Some developer tools and AI coding assistants do read llms.txt files, mainly for software documentation.",
      "So for a contractor, an llms.txt file is best thought of as low-cost and low-risk with uncertain benefit. It won't hurt, it takes little time, and if more AI tools adopt it, you'll already have one. But it's not going to move the needle on its own.",
      "## What matters far more for AI visibility",
      "If you're deciding where to spend time, these have a much clearer impact on whether AI assistants find and recommend you:",
      "### Don't block the crawlers that matter",
      "Check your robots.txt file. Some websites accidentally block crawlers that AI search tools use to find content, such as OAI-SearchBot for ChatGPT search, PerplexityBot, Bingbot and Googlebot. If those are blocked, your pages may not show up in those tools at all.",
      "### Make your business details consistent",
      "Your name, phone, service area and services should match across your website, Google Business Profile, Bing Places, Apple Business Connect and directories. See [how AI assistants choose which businesses to recommend](/blog/how-ai-assistants-choose-businesses).",
      "### Write clear, specific service pages",
      "Pages that directly answer what you do, where, how long it takes and what affects the price give AI tools something to quote.",
      "### Add structured data",
      "Schema markup labels your business details in a standard, widely supported format. Unlike llms.txt, it's used by Google and other search engines. See [schema markup explained](/blog/schema-markup-explained).",
      "### Earn reviews and mentions",
      "Independent evidence that you're good at what you do is one of the strongest signals for AI recommendations.",
      "## How to add an llms.txt file",
      "If you'd like one, it's straightforward:",
      "- Create a plain text file named llms.txt.",
      "- Start with your business name as a heading and a short description of what you do and where.",
      "- Add sections, such as Services and Company, each with a list of links to key pages and a one-line description of each.",
      "- Upload it to the root of your website so it loads at yoursite.com/llms.txt.",
      "- Update it whenever your services, pricing or key pages change.",
      "Keep it accurate and short. It should summarize your site, not repeat it.",
      "![A contractor and a web designer reviewing website files together at a desk](/blog/img/what-is-llms-txt-2.webp \"Adding llms.txt takes minutes, but the basics of AI visibility matter much more.\")",
      "## Our approach",
      "Every website we build includes an llms.txt file, because it's quick and harmless. But we're honest with clients that it's a small extra, not a strategy. The work that actually improves AI visibility is the consistent listings, strong service pages, structured data and reviews described above.",
      "## The bottom line",
      "llms.txt is a reasonable, low-effort addition to a business website, but its real-world impact on AI search is unproven. Add one if it's easy, then spend your real effort on the fundamentals that AI tools clearly do use.",
      "Want to know what's actually helping or holding back your AI visibility? [Request a free AI visibility audit](/contact?interest=audit), or read [what AI SEO is](/blog/what-is-ai-seo) for the full picture.",
    ],
  },
  {
    slug: "ai-seo-vs-traditional-seo",
    title: "AI SEO vs Traditional SEO: What's Different and What Still Matters",
    metaDescription: "Is AI SEO a replacement for traditional SEO? How optimizing for ChatGPT, Gemini and AI Overviews differs from classic Google SEO, where they overlap, and how contractors should split their effort.",
    excerpt: "AI SEO doesn't replace traditional SEO. It builds on it. Here's what's genuinely different and where contractors should focus.",
    category: "AI Search",
    keywords: ["AI SEO", "traditional SEO", "generative engine optimization", "search strategy"],
    content: [
      "Every few years, someone declares that SEO is dead. With AI assistants now answering questions directly, the claim is back. The reality is less dramatic: AI search has changed what success looks like and shifted some priorities, but the foundations of SEO still carry most of the weight.",
      "Here's a practical comparison for contractors who want to know where to put their time and budget.",
      "## What traditional SEO aims for",
      "Classic SEO is about ranking well in Google's results so people click through to your website. For local businesses, that means two places: the map results, driven mostly by your Google Business Profile, and the regular organic results below them, driven by your website.",
      "The main levers are familiar:",
      "- Relevant pages targeting the searches customers make.",
      "- A complete, active Google Business Profile.",
      "- Reviews and local reputation.",
      "- Links from other reputable websites.",
      "- A fast, technically sound website.",
      "## What AI SEO aims for",
      "AI SEO, sometimes called generative engine optimization, is about being mentioned and recommended inside AI-generated answers: ChatGPT, Gemini, Perplexity, Copilot, and Google's AI Overviews and AI Mode. Success isn't a ranking position. It's being one of the few businesses named when someone asks, 'Who should I hire for this?'",
      "![A side-by-side of a classic search results page and an AI assistant answer on two screens](/blog/img/ai-seo-vs-traditional-seo-1.webp \"Traditional SEO earns a ranking. AI SEO earns a mention in the answer.\")",
      "## Where they overlap",
      "Most of the work is shared. AI tools frequently pull from search indexes, business listings and review sites, which are the same things traditional SEO builds. That means:",
      "- **Indexed, crawlable pages** are required for both.",
      "- **A strong Google Business Profile** feeds both Google's map results and Google's AI features.",
      "- **Reviews** improve local rankings and give AI tools evidence that you're good at specific jobs.",
      "- **Helpful, specific content** ranks better and gets quoted more.",
      "If your traditional SEO is weak, AI SEO has very little to build on.",
      "## What's genuinely different",
      "### Consistency matters even more",
      "Google has decades of practice matching business listings. AI assistants pulling from many sources can get confused by an old phone number on Yelp or a different business name on Facebook. Consistent details across every listing, including Bing Places and Apple Business Connect, carry more weight.",
      "### Mentions matter, not just links",
      "Traditional SEO prizes backlinks. AI tools also seem to value mentions of your business on trusted sites, even without a link: a local news story, an association member page, a supplier's list of certified installers. Being talked about counts.",
      "### Direct, quotable answers win",
      "Ranking a page and getting a passage quoted are different. AI tools favour clear statements that answer a question on their own, such as 'Most furnace replacements take one day, including removing the old unit, installing the new one and testing it before we leave.' Pages written in that style serve both purposes.",
      "### Visibility is harder to measure",
      "You can track a Google ranking. AI answers vary from person to person and day to day. Measuring AI visibility means regularly asking assistants the questions your customers ask and recording whether you're mentioned, how you're described and which sources are cited.",
      "### Fewer winners per answer",
      "A search results page shows ten organic links plus the map pack. An AI answer might name three businesses. The gap between being mentioned and being invisible is wider.",
      "## A side-by-side summary",
      "- **Goal:** traditional SEO earns a ranking and a click. AI SEO earns a mention and a recommendation.",
      "- **Main inputs:** both rely on your website, Business Profile and reviews. AI SEO adds more weight to consistent listings everywhere and mentions on other sites.",
      "- **Content style:** both reward helpful content. AI SEO especially rewards direct, quotable answers.",
      "- **Measurement:** traditional SEO uses rankings, traffic and Search Console. AI SEO uses regular prompt testing and citation tracking.",
      "- **Timeline:** both build over months, not days.",
      "![A contractor reviewing search and AI visibility reports with a marketing consultant](/blog/img/ai-seo-vs-traditional-seo-2.webp \"Most of the work serves both. The difference is in emphasis and measurement.\")",
      "## How contractors should split their effort",
      "For most local service businesses, we recommend this order:",
      "- **First, the shared foundation:** a complete Business Profile, a fast website with a page for each service, consistent listings, and a steady flow of reviews.",
      "- **Second, AI-specific polish:** Bing Places and Apple Business Connect, structured data, direct-answer content and FAQs, and earning mentions from local organizations.",
      "- **Third, measurement:** track calls and booked jobs from search, and test regularly how AI assistants describe you.",
      "You don't need two separate strategies. You need one strategy that's built with both kinds of search in mind.",
      "## The bottom line",
      "AI SEO isn't a replacement for traditional SEO. It's an extension of it. Businesses with strong local SEO already have most of what AI tools look for, and the AI-specific work builds on that foundation rather than starting from scratch.",
      "Our Growth and Authority plans cover both. Learn more in [what AI SEO is](/blog/what-is-ai-seo) and the [local SEO guide](/blog/local-seo-guide), or [request a free AI visibility audit](/contact?interest=audit) to see where you stand.",
    ],
  },
  {
    slug: "local-seo-guide",
    title: "Local SEO in 2026: How GTA Contractors Show Up When Customers Search Near Them",
    metaDescription: "A practical local SEO guide for GTA contractors: how Google decides who shows up on Maps, what to fix first, and how to grow calls from local search without gimmicks.",
    excerpt: "When a homeowner searches for a contractor near them, Google shows a handful of businesses on a map. Here's how to become one of them.",
    category: "SEO",
    keywords: ["local SEO", "Google Maps ranking", "contractor SEO", "near me searches"],
    content: [
      "When a homeowner in Etobicoke searches 'electrician near me', Google shows a map with three businesses underneath, then a list of regular results, and often some ads above both. Most of the calls go to the businesses in that map section. Local SEO is the work of earning a place there, and in the regular results below it.",
      "This guide covers what actually moves the needle for contractors in the GTA, in the order we'd tackle it.",
      "## How Google decides who shows up locally",
      "Google is unusually open about this. Local results are based mainly on three factors:",
      "- **Relevance:** how well your business matches what was searched. If someone searches 'heat pump installation', a business that clearly lists heat pump installation is more relevant than one that just says 'HVAC'.",
      "- **Distance:** how far your business is from the searcher or the location in their search. You can't change where you're based, but you can make your service area clear.",
      "- **Prominence:** how well known and well regarded your business is, based on things like reviews, links, mentions across the web and your overall search presence.",
      "Everything in local SEO works on one or more of these three.",
      "![A smartphone showing a Google Maps search with business pins spread across a suburban neighbourhood](/blog/img/local-seo-guide-1.webp \"Most local calls start from the map results, so that's where to focus first.\")",
      "## Step 1: Get your Google Business Profile right",
      "Your Business Profile is the single most important local SEO asset you have. It's what appears in the map results. Make sure it's verified, uses your real business name, has the most specific primary category, lists every service, shows your service areas, and is full of real photos. We walk through every setting in our [Google Business Profile guide](/blog/google-business-profile-optimization).",
      "## Step 2: Build a page for each service",
      "Google needs to see that you're relevant for each service you want to be found for. A single 'Services' page with a list won't do it. Give each main service its own page that explains what's involved, the problems it solves, rough timelines, what affects the price, and the questions customers ask. Link to these pages from your Business Profile and your homepage.",
      "## Step 3: Show your service area honestly",
      "Most contractors are service-area businesses: you go to customers rather than customers coming to you. Make your service area clear on your website and your Business Profile.",
      "If you want pages for specific cities, make each one genuinely useful: jobs you've completed there, local housing considerations (older homes in the Junction, newer subdivisions in Brampton), and reviews from customers in that area. Creating dozens of near-identical pages that only swap the city name is what Google calls doorway pages, which are against its spam policies and can hurt you.",
      "## Step 4: Make your business details consistent everywhere",
      "Your business name, phone number, website and address (if you show one) should match exactly across your website, Google, Bing Places, Apple Business Connect, Yelp, YellowPages.ca, the Better Business Bureau, and home-service directories like HomeStars and Houzz. Inconsistent details, such as an old phone number or a former address, create doubt for search engines and AI tools alike.",
      "## Step 5: Earn reviews, constantly",
      "Reviews feed directly into prominence, and Google says review count and rating factor into local ranking. They also decide who gets the call once someone sees the map. The key is consistency: ask every customer, right after the job, with a direct link. Our post on [Google reviews and AI search](/blog/google-reviews-and-ai-search) covers how to do it within Google's rules.",
      "## Step 6: Earn local links and mentions",
      "Links from other reputable local websites tell Google you're a real, established part of the community. For contractors, good sources include:",
      "- Manufacturer and supplier dealer locators, such as an HVAC brand's dealer finder.",
      "- Trade associations and certification programs.",
      "- Your local chamber of commerce or BIA.",
      "- Sponsorships of youth sports teams, charity events and community festivals.",
      "- Local news coverage of a notable project or community involvement.",
      "A handful of genuine local links is worth far more than hundreds of low-quality ones bought online.",
      "## Step 7: Cover the technical basics",
      "Your website should load quickly on phones, use HTTPS, have a clear page title and description on every page, and include local business structured data. None of this is glamorous, but problems here can quietly hold everything else back. See [technical SEO basics](/blog/technical-seo-basics).",
      "## What about ads?",
      "Google Ads and Local Services Ads can put you at the top of the page right away, while SEO builds over time. Many contractors use both: ads for immediate leads, SEO for long-term, lower-cost visibility. We compare them in [Google Ads vs SEO](/blog/google-ads-vs-seo).",
      "![A contractor's work truck parked on a residential street in a GTA neighbourhood](/blog/img/local-seo-guide-2.webp \"Local SEO is about being the obvious choice in the neighbourhoods you actually serve.\")",
      "## How to track progress",
      "Rankings for a single keyword bounce around and depend on where the searcher is standing, so don't obsess over one number. Watch the trends that matter:",
      "- Calls, website clicks and direction requests in your Business Profile performance report.",
      "- Search impressions and clicks in Google Search Console.",
      "- Calls and form submissions tracked on your website.",
      "- Most importantly, estimates booked and jobs won from local search.",
      "## How long does it take?",
      "Fixing your Business Profile and reviews can show results within weeks. Content, service pages and local links typically take several months to build momentum, and competitive trades in dense parts of the GTA take longer. We explain realistic timelines in [how long SEO takes](/blog/how-long-does-seo-take).",
      "## The bottom line",
      "Local SEO isn't about tricks. It's about giving Google clear proof that you do the job, in the area, and that customers trust you. Get your Business Profile right, build real service pages, keep your details consistent, and earn reviews and local mentions month after month.",
      "Local SEO is part of our Growth and Authority plans. Want to know where you stand right now? [Request a free audit](/contact?interest=audit) and we'll show you what to fix first.",
    ],
  },
  {
    slug: "google-business-profile-optimization",
    title: "How to Optimize Your Google Business Profile: A Step-by-Step Guide for Contractors",
    metaDescription: "Your Google Business Profile decides whether you show up on Google Maps. A step-by-step guide for contractors: categories, service areas, photos, reviews and the mistakes that get profiles suspended.",
    excerpt: "Your Google Business Profile is often the first thing a homeowner sees. Here's how to set up every part of it properly, step by step.",
    category: "SEO",
    keywords: ["Google Business Profile", "Google Maps", "local SEO checklist", "contractor Google listing"],
    content: [
      "For most contractors, your Google Business Profile does more selling than your website. It's what appears in the map results when someone searches for your trade nearby, and it's often the first and only thing a homeowner looks at before calling. A complete, accurate, active profile gets more calls. A thin or neglected one gets skipped.",
      "Here's how to set up every part of it properly, in order.",
      "## 1. Claim and verify your profile",
      "Search for your business on Google Maps. If a profile already exists, claim it. If not, create one at business.google.com. Google will then ask you to verify that you're the real owner. These days that's often a short video showing your business, such as your branded vehicle, tools, business documents and the area you work in. Follow the instructions exactly, because unverified profiles don't show up properly.",
      "Use a business email you control as the owner, and add your office manager or marketing partner as a manager rather than handing over the owner login.",
      "## 2. Use your real business name",
      "Your profile name must match the name you use in the real world: on your truck, invoices and signage. Adding keywords, like 'Northline Plumbing | Emergency Plumber Vaughan', is against Google's guidelines and is one of the most common reasons profiles get suspended. It may give a short-term bump, but it's not worth the risk.",
      "## 3. Choose the right categories",
      "Your primary category is one of the strongest signals for which searches you appear in. Choose the most specific one that describes your core business, such as 'Plumber', 'HVAC contractor', 'Roofing contractor' or 'Electrician'. Then add secondary categories for other services you genuinely offer, like 'Water heater installation service' or 'Air conditioning repair service'. Don't add categories for work you don't do.",
      "## 4. Set up your service area correctly",
      "Most contractors are service-area businesses: you travel to customers. If customers don't come to your address, Google's guidelines say to hide it and list your service areas instead. You can add up to 20 service areas, such as cities or postal-code areas, and Google recommends keeping them within about two hours' driving distance of your base.",
      "Never use a virtual office, a mailbox store or a relative's house as your address to appear in a city where you don't actually operate. It violates Google's guidelines and is a common cause of suspensions.",
      "![A contractor photographing a newly installed furnace with his phone for his Google Business Profile](/blog/img/google-business-profile-optimization-1.webp \"Real photos of your own work are some of the most persuasive things on your profile.\")",
      "## 5. Add accurate hours, phone and website",
      "List your regular hours and update them for holidays. If you offer emergency service, make it clear in your services and description, but only list 24-hour hours if someone actually answers.",
      "Use your main business phone number, the same one on your website. Link to your homepage or your most relevant page. Adding tracking parameters to that link lets you see in your analytics exactly how many visits come from your profile.",
      "## 6. List every service",
      "Add each service you offer with a short, plain-language description. This helps you show up for specific searches, and homeowners read these lists to check that you do what they need. Be specific: 'Furnace repair', 'Furnace installation', 'Heat pump installation' and 'Duct cleaning' are better than one generic 'Heating services'.",
      "## 7. Write a useful description",
      "You have 750 characters to describe your business. Say what you do, where you work, what makes you different, and how long you've been doing it. Write it for homeowners, not for keywords, and don't include links or promotions.",
      "## 8. Upload real photos regularly",
      "Add your logo and a cover photo, then keep adding real photos: finished jobs, before-and-after shots, your team, your trucks. Photos of actual work build trust in a way stock images can't. Adding a few new ones every month also signals that your business is active.",
      "## 9. Post updates",
      "Google lets you publish short posts on your profile: seasonal tune-up reminders, recent projects, offers or helpful tips. They don't need to be elaborate. Posting regularly keeps your profile fresh and gives homeowners one more reason to choose you.",
      "## 10. Earn and respond to reviews",
      "Reviews are a major factor in both ranking and conversion. Ask every customer, right after the job, with a direct link to your review form. Reply to every review, positive or negative, politely and specifically. Our guide to [Google reviews in the age of AI search](/blog/google-reviews-and-ai-search) covers the right way to ask and the rules to follow.",
      "## 11. Turn on the right contact options",
      "Google discontinued Business Profile chat in 2024, so customers can no longer message you directly through your listing. That makes the other routes more important: a clearly listed phone number backed by [missed call text back](/blog/missed-call-text-back), and a website with [AI chat](/blog/ai-website-chat-vs-contact-forms) and online booking where it fits your business.",
      "## 12. Keep it accurate",
      "Anyone can suggest edits to a public profile, and Google sometimes applies them automatically. Log in regularly to check that your hours, phone number, categories and website are still correct, and review any changes Google suggests.",
      "![A tradesperson checking his Google Business Profile insights on a phone outside a client's home](/blog/img/google-business-profile-optimization-2.webp \"Check your profile regularly to keep details accurate and see how many calls it brings in.\")",
      "## Mistakes that get profiles suspended",
      "A suspended profile disappears from Maps, sometimes for weeks. Avoid these common causes:",
      "- Stuffing keywords or city names into your business name.",
      "- Using a virtual office, mailbox or fake address.",
      "- Creating more than one profile for the same business.",
      "- Buying reviews, reviewing yourself, or offering incentives for reviews.",
      "- Listing services or locations you don't actually cover.",
      "## How to measure results",
      "Your profile's performance report shows how many people called, requested directions, visited your website or found you through searches. Watch those numbers month to month, and connect them to the jobs you actually win.",
      "## The bottom line",
      "Your Google Business Profile is free, and for many contractors it's the most valuable marketing asset they have. Set up every section properly, keep it accurate, keep adding photos and reviews, and stay well within Google's guidelines.",
      "Google Business Profile optimization is included in our Growth and Authority plans. Not sure how yours stacks up? [Request a free audit](/contact?interest=audit) and we'll show you what to fix.",
    ],
  },
  {
    slug: "technical-seo-basics",
    title: "Technical SEO Basics: A Plain-English Checklist for Contractor Websites",
    metaDescription: "Technical SEO makes sure Google can find, read and trust your website. A plain-English checklist for contractors: indexing, speed, mobile, HTTPS, structure and the free tools to check it.",
    excerpt: "Technical SEO is the plumbing behind your website. If it's broken, nothing else works properly. Here's what to check, in plain English.",
    category: "SEO",
    keywords: ["technical SEO", "Google Search Console", "website indexing", "contractor website SEO"],
    content: [
      "Think of technical SEO as the plumbing and wiring behind your website. Homeowners never see it, but if it's faulty, nothing else works properly. You can write great service pages and earn hundreds of reviews, and still struggle in search because Google can't properly find, load or understand your site.",
      "The good news is that technical SEO for a typical contractor website isn't complicated. Here's a plain-English checklist, roughly in order of importance, plus the free tools to check each item.",
      "## 1. Set up Google Search Console",
      "Before anything else, set up Google Search Console. It's free, and it's Google telling you directly how it sees your site: which pages are indexed, which have problems, what searches you appear for, and how many clicks you get. If you only set up one tool, make it this one. Do the same with Bing Webmaster Tools, which also feeds Microsoft's Copilot.",
      "## 2. Make sure your pages are indexed",
      "A page that isn't in Google's index can't appear in search or in Google's AI features. In Search Console, the Pages report shows which pages are indexed and why others aren't. Common culprits:",
      "- **A 'noindex' tag left on by accident**, often after a website launch or redesign.",
      "- **Pages blocked in robots.txt**, the file that tells crawlers what they can access.",
      "- **Duplicate pages** that Google has decided not to index.",
      "- **Thin or near-identical pages**, such as city pages with only the name swapped.",
      "![A contractor reviewing a Google Search Console indexing report on a laptop in his garage office](/blog/img/technical-seo-basics-1.webp \"Search Console shows exactly which pages Google has indexed, and why some aren't.\")",
      "## 3. Submit a sitemap",
      "A sitemap is a list of the pages on your site, usually at yoursite.com/sitemap.xml. Most website platforms create one automatically. Submit it in Search Console so Google knows where to find everything, especially new service and blog pages.",
      "## 4. Check robots.txt",
      "Your robots.txt file sits at yoursite.com/robots.txt. It should allow search engines to crawl your public pages. Make sure it isn't blocking your whole site, which happens more often than you'd think after a redesign, and isn't blocking the crawlers AI search tools use, such as Bingbot, OAI-SearchBot and PerplexityBot.",
      "## 5. Use HTTPS everywhere",
      "Your site should load securely over HTTPS, with a padlock in the browser bar. Sites without it show a 'Not secure' warning that scares visitors away. Make sure every page uses HTTPS and that the old http:// version redirects to it.",
      "## 6. Make it work well on phones",
      "Google primarily uses the mobile version of your site to understand and rank it, and most homeowners find contractors on their phones anyway. Text should be readable without zooming, buttons easy to tap, and nothing should spill off the screen. Test your key pages on your own phone, not just a desktop browser.",
      "## 7. Make it fast",
      "Google's Core Web Vitals measure real-world loading experience:",
      "- **Largest Contentful Paint (LCP):** the main content should appear within 2.5 seconds.",
      "- **Interaction to Next Paint (INP):** the page should respond to taps and clicks within 200 milliseconds.",
      "- **Cumulative Layout Shift (CLS):** the layout shouldn't jump around while loading. Aim for 0.1 or less.",
      "Check them with Google's free PageSpeed Insights. On contractor sites, oversized photos are the most common problem by far. More in [how website speed costs you customers](/blog/website-speed-costs-customers).",
      "## 8. Give every page a clear title and description",
      "Each page needs its own title tag, which appears as the clickable headline in search results, and a meta description, which often appears beneath it. Make them specific: 'Furnace Repair in Vaughan | Same-Day Service | Northline Heating' beats 'Home | Northline'. Avoid using the same title on multiple pages.",
      "## 9. Use a clean page structure",
      "Each page should have one main heading (H1) that says what the page is about, with subheadings (H2, H3) that organize the content logically. This helps both readers scanning on a phone and search engines understanding the page.",
      "## 10. Fix broken links and use redirects",
      "Broken links frustrate visitors and waste the attention search engines give your site. When you remove or rename a page, set up a permanent (301) redirect from the old address to the most relevant new one. This is especially important after a website rebuild, when old page addresses often change. See [7 signs your website needs a rebuild](/blog/signs-your-website-needs-a-rebuild).",
      "## 11. Add structured data",
      "Structured data labels your business details, services and content so search engines and AI tools can read them without guessing. Use the specific type for your trade, such as Plumber or RoofingContractor. See [schema markup explained](/blog/schema-markup-explained).",
      "## 12. Link your pages together sensibly",
      "Internal links help visitors and search engines move between related pages: from a blog post about furnace noises to your furnace repair page, for example. See [internal linking strategy](/blog/internal-linking-strategy).",
      "![A web developer and a contractor going through a website checklist together at a desk](/blog/img/technical-seo-basics-2.webp \"Most technical fixes are one-time jobs. After that, a monthly check keeps things healthy.\")",
      "## How often to check",
      "Most of this is set up once. After that, a quick monthly look at Search Console catches new problems early: pages dropping out of the index, new errors, or a sudden fall in clicks. Check again after any website change, plugin update or redesign.",
      "## The bottom line",
      "Technical SEO isn't glamorous, but it's the foundation everything else sits on. Get Google able to find, load and understand every important page, keep the site fast and mobile-friendly, and the rest of your SEO work has a fair chance to pay off.",
      "Technical SEO monitoring is included in our Growth and Authority plans. If you're not sure whether your site has hidden problems, [request a free audit](/contact?interest=audit) and we'll check.",
    ],
  },
  {
    slug: "keyword-research-for-small-business",
    title: "Keyword Research for Contractors: How to Find What GTA Homeowners Actually Search",
    metaDescription: "Keyword research tells you the words homeowners use when they need your services. A simple, free method for contractors to find the right keywords and turn them into pages that bring in calls.",
    excerpt: "Homeowners don't search the way contractors talk. Keyword research shows you the words they actually use, and which ones bring in jobs.",
    category: "SEO",
    keywords: ["keyword research", "contractor keywords", "local SEO keywords", "small business SEO"],
    content: [
      "Contractors often describe their work in trade terms. Homeowners search in their own words. An HVAC company might talk about 'heat pump retrofits' while homeowners type 'cost to replace furnace with heat pump Ontario'. A roofer says 'eavestrough installation'; some customers search 'gutters'. Keyword research closes that gap.",
      "It's simply the process of finding out which words and phrases your potential customers use when they're looking for what you do, then building pages that match. You don't need expensive tools to do it well.",
      "## Know the three types of searches",
      "Not all keywords are equal. For contractors, they fall into three broad groups:",
      "- **Ready to hire:** 'emergency plumber Mississauga', 'roof repair near me', 'furnace installation Vaughan'. These are the most valuable. People searching them want to book someone now.",
      "- **Researching a problem:** 'why is my basement wet after rain', 'furnace making banging noise'. These people have a problem and may hire soon.",
      "- **Researching cost and options:** 'how much does a new roof cost in Ontario', 'heat pump vs furnace'. These people are planning and comparing.",
      "Your service pages should target the first group. Blog posts and guides work well for the second and third, which also build trust before someone is ready to call.",
      "![A small business owner writing keyword ideas in a notebook beside a laptop at a kitchen table](/blog/img/keyword-research-for-small-business-1.webp \"Start with the questions customers ask you on every estimate.\")",
      "## Free ways to find keywords",
      "### 1. Start with your own customers",
      "The best keyword list starts with the questions you hear every week. Write down what customers ask on the phone and during estimates, and the exact words they use. These are the searches they made before they found you.",
      "### 2. Use Google's autocomplete",
      "Start typing a search, like 'basement waterproofing' or 'furnace repair', and look at what Google suggests. Those suggestions come from real searches. Try adding your city, or words like 'cost', 'near me' and 'how to'.",
      "### 3. Look at 'People also ask'",
      "Many search results include a 'People also ask' box with related questions. Each one is a real question homeowners have and a potential section on your page or a blog post.",
      "### 4. Check Google Search Console",
      "If your site is already set up in Search Console, the Performance report shows the actual searches people used to find you, including ones you never deliberately targeted. It often reveals opportunities, like a page that gets impressions for 'water heater rental buyout' even though you've never written about it.",
      "### 5. Use Google Keyword Planner",
      "Google's Keyword Planner, available free inside a Google Ads account, gives rough search volumes and related ideas. The numbers are broad ranges, but they're useful for comparing options.",
      "### 6. Look at your competitors",
      "Look at the websites of contractors who show up above you. Which services have their own pages? Which questions do they answer? You're not copying them, just making sure you're not missing what homeowners expect to find.",
      "## Think local, and think Canadian",
      "Local wording matters. A few examples from the GTA:",
      "- Canadians often search 'eavestrough' as well as 'gutter'.",
      "- Older Toronto homes create searches like 'knob and tube wiring replacement' and 'basement underpinning'.",
      "- Basement flooding drives searches for 'backwater valve installation' and 'sump pump installation'.",
      "- Many people add the city: 'Etobicoke', 'Scarborough' and 'North York' are searched alongside 'Toronto'.",
      "Use the words your customers use, in the places they live.",
      "## Turn keywords into pages",
      "Once you have a list, group similar keywords together. Each group becomes one page, not one page per keyword. For example:",
      "- **Furnace repair page:** furnace repair, furnace not working, furnace making noise, no heat emergency.",
      "- **Furnace installation page:** furnace replacement, new furnace cost, high-efficiency furnace install.",
      "- **Blog post:** 'Should I repair or replace my furnace?'",
      "Then write each page for the person, not the keyword. Use the main phrase naturally in the title, the main heading and the opening paragraph, and answer the related questions in the body. Repeating a keyword over and over doesn't help and reads badly.",
      "![A contractor mapping groups of keywords to website pages on a whiteboard in a small office](/blog/img/keyword-research-for-small-business-2.webp \"Group related keywords together, then give each group one strong page.\")",
      "## Mistakes to avoid",
      "- **Chasing big, broad terms** like 'contractor' or 'roofing' instead of specific, local, ready-to-hire searches.",
      "- **Making a page for every tiny variation**, which spreads your effort thin and creates near-duplicate pages.",
      "- **Copying city pages** with only the location swapped, which Google treats as spam.",
      "- **Ignoring the questions** customers ask, which are often the easiest wins.",
      "## The bottom line",
      "Good keyword research isn't about tools. It's about listening to how customers describe their problems, confirming it with free data, and building clear pages that match. Do that, and you'll show up for the searches that actually lead to jobs.",
      "Keyword research and content planning are part of our Growth and Authority plans. Next, read our [local SEO guide](/blog/local-seo-guide) or [how often a business should blog](/blog/how-often-should-a-business-blog).",
    ],
  },
  {
    slug: "how-long-does-seo-take",
    title: "How Long Does SEO Take? Realistic Timelines for Contractors",
    metaDescription: "How long until SEO brings in calls? Realistic timelines for contractors in the GTA: what changes in weeks, what takes months, what affects the pace, and how to judge progress along the way.",
    excerpt: "SEO isn't instant, but it isn't a mystery either. Here's what changes in weeks, what takes months, and how to tell if it's working.",
    category: "SEO",
    keywords: ["how long does SEO take", "SEO timeline", "local SEO results", "contractor marketing"],
    content: [
      "It's the first question almost every contractor asks: how long until SEO actually brings in calls? It's a fair question, especially when you're paying every month. The honest answer is that it depends, but not in a vague, hand-waving way. There are clear stages, and you can see progress at each one.",
      "Google itself says that, in most cases, it takes four months to a year for SEO work to be implemented and to start showing benefits. Here's what that looks like in practice for a local contractor.",
      "## Weeks 1 to 4: fixing the foundations",
      "The first month is mostly setup and repair:",
      "- Setting up or fixing Google Search Console and analytics.",
      "- Fixing technical problems like pages that aren't indexed, slow loading or broken links.",
      "- Completing and correcting your Google Business Profile.",
      "- Making your business details consistent across directories.",
      "- Starting a steady review request process.",
      "Some of this can show results quickly. Fixing a broken Business Profile, adding missing categories or recovering pages that weren't indexed can produce noticeable gains within weeks. But most of the work in this phase is laying groundwork.",
      "![A young tree recently planted in a suburban front yard next to a fully grown tree](/blog/img/how-long-does-seo-take-1.webp \"SEO compounds over time. Early work sets up the growth that follows.\")",
      "## Months 2 to 4: early movement",
      "As new service pages, content and listings are added, you should start seeing early signals:",
      "- More impressions in Search Console, meaning Google is showing your pages for more searches.",
      "- Rankings appearing for longer, more specific searches, like 'sump pump replacement Woodbridge'.",
      "- More views and actions on your Business Profile.",
      "- A handful of calls and form submissions from search.",
      "This is the stage where many businesses give up because the phone isn't ringing off the hook yet. But these signals are exactly what comes before growth.",
      "## Months 4 to 12: compounding results",
      "This is where SEO starts paying off. As your pages build authority, your reviews accumulate and other sites mention you, you begin ranking for broader, more competitive searches and appearing more often in the map results. Leads become steadier and less dependent on ads or referrals.",
      "Unlike ads, which stop the moment you stop paying, the results from SEO tend to stick around and build on each other.",
      "## What affects the pace",
      "Every business starts from a different place. These factors make the biggest difference:",
      "### Your trade and your area",
      "An emergency plumber in downtown Toronto faces far more competition than a pool installer in Caledon. Dense, high-value trades in competitive parts of the GTA take longer.",
      "### Where you're starting from",
      "A new business with a brand-new website and no reviews starts from zero. An established company with a decent site and 80 reviews can move much faster.",
      "### Your reviews",
      "Reviews feed directly into local rankings. Businesses that consistently ask every customer for a review tend to progress noticeably faster. See [why Google reviews matter](/blog/google-reviews-and-ai-search).",
      "### How much gets done",
      "Publishing a few strong pages every month moves faster than one page a quarter. Consistency matters more than bursts.",
      "### Your website",
      "A slow, outdated or poorly built website holds everything back. Sometimes the fastest path is fixing or rebuilding the site first. See [7 signs your website needs a rebuild](/blog/signs-your-website-needs-a-rebuild).",
      "## How to tell if it's working before the calls arrive",
      "Don't judge SEO only on calls in the first few months. Look at the leading signals:",
      "- **Search Console impressions and clicks** are trending up.",
      "- **More of your important pages** are indexed and ranking for something.",
      "- **Business Profile calls, clicks and direction requests** are increasing.",
      "- **Your review count** is growing every month.",
      "- **Specific searches** you care about are moving up, even from page three to page two.",
      "If these are improving month over month, results are coming. If nothing has moved after four to six months of real work, something needs to change, and a good agency should tell you so.",
      "![A contractor and marketer reviewing a chart of steadily rising search impressions on a laptop](/blog/img/how-long-does-seo-take-2.webp \"Rising impressions and rankings come before rising calls.\")",
      "## Be wary of fast promises",
      "Anyone who guarantees first-page rankings in 30 days, or a number-one spot on Google, is either using tactics that can get you penalized or overselling. Google's own guidance says nobody can guarantee a number-one ranking.",
      "## What to do while SEO builds",
      "SEO is a long-term investment, but you still need leads now. Two things help in the meantime:",
      "- **Paid ads** can bring in leads immediately while organic results grow. See [Google Ads vs SEO](/blog/google-ads-vs-seo).",
      "- **Capturing every lead you already get** often delivers the fastest return of all. Missed call text back, fast follow-up and AI chat make sure the leads you have don't slip away. See [speed to lead](/blog/speed-to-lead).",
      "## The bottom line",
      "Expect foundations in the first month, early signals within two to four months, and compounding results from about four months to a year, faster or slower depending on your trade, area and starting point. Judge progress by the leading signals, not just the phone, and stick with it long enough for the work to pay off.",
      "Our Growth and Authority plans include monthly reporting on exactly these signals, so you can see progress before the calls arrive. [Book a call](/contact) to talk about realistic goals for your business.",
    ],
  },
  {
    slug: "internal-linking-strategy",
    title: "Internal Linking: The Simple SEO Habit Most Contractor Websites Ignore",
    metaDescription: "Internal links connect the pages on your website. Done well, they help visitors find what they need and help Google understand your services. A simple internal linking strategy for contractors.",
    excerpt: "Internal links are the hallways of your website. They guide visitors and Google to the pages that matter. Here's how to use them well.",
    category: "SEO",
    keywords: ["internal linking", "on-page SEO", "website structure", "contractor website SEO"],
    content: [
      "Think of your website like a house. Each page is a room, and internal links are the hallways and doorways between them. If the hallways make sense, visitors find what they're looking for, and so does Google. If rooms are sealed off with no doors, nobody ever finds them.",
      "Internal links are simply links from one page on your website to another. They're one of the easiest SEO improvements a contractor can make, and one of the most often ignored.",
      "## Why internal links matter",
      "### They help visitors take the next step",
      "Someone reading a blog post about why their furnace keeps shutting off is a strong lead. A link to your furnace repair page, or to book an appointment, gives them an obvious next step. Without it, they finish reading and leave.",
      "### They help Google find your pages",
      "Google discovers pages largely by following links. A service page that nothing links to is harder for Google to find and may be treated as unimportant.",
      "### They tell Google what your pages are about",
      "The words you use in a link, called anchor text, give Google context about the page it points to. A link that says 'furnace repair in Vaughan' tells Google much more than one that says 'click here'.",
      "### They show which pages matter most",
      "Pages that many other pages link to are signalled as important. Your main service pages should be the most linked-to pages on your site.",
      "![A bright hallway in a modern home with open doors leading into several rooms](/blog/img/internal-linking-strategy-1.webp \"Internal links are the hallways of your website, connecting every room to the ones that matter.\")",
      "## A simple internal linking structure for contractors",
      "Most contractor websites work well with a straightforward structure:",
      "- **The homepage** links to every main service page and your most important area pages.",
      "- **Each service page** links to related services, your booking or contact page, and relevant guides.",
      "- **Each blog post** links to the service page it relates to, plus one or two related posts.",
      "- **Area pages**, if you have them, link to the services you offer in that area.",
      "This creates clear paths: a homeowner can land on any page and move naturally toward booking you.",
      "## Practical rules that work",
      "### Use descriptive link text",
      "Write links that describe where they go. 'See our [guide to missed call text back](/blog/missed-call-text-back)' is better than 'click here'. Keep it natural. You don't need the exact keyword every time, and forcing it reads badly.",
      "### Link from blog posts to service pages",
      "This is the most valuable habit to build. Every blog post should point readers toward the service it relates to. A post about ice dams should link to your roof repair page. A post about tripping breakers should link to your panel upgrade page.",
      "### Link new pages from existing ones",
      "When you publish a new service page or post, go back to two or three older related pages and add a link to it. Otherwise, new pages can sit undiscovered for weeks.",
      "### Keep it useful, not excessive",
      "Add links where they genuinely help the reader. A handful of relevant links per page is plenty. Twenty links crammed into a short post distract readers and dilute the value of each one.",
      "### Fix broken links",
      "When pages are renamed or removed, links pointing to them break. Check for broken internal links regularly and update them, or set up redirects from old addresses.",
      "## Watch out for orphan pages",
      "An orphan page is a page that no other page on your site links to. Orphan pages are hard for visitors and search engines to find, and they're common on contractor sites: an old service page left off the menu, or a landing page made for an ad campaign. Make sure every page you want found is linked from somewhere sensible.",
      "## Menus, footers and breadcrumbs count too",
      "Your main navigation menu, footer links and breadcrumbs, the small 'Home > Services > Furnace Repair' trail at the top of a page, are all internal links. Make sure your menu includes your main services, keep the footer tidy, and use breadcrumbs on deeper pages so visitors always know where they are.",
      "![A contractor reviewing a map of website pages and links with a web designer on a laptop](/blog/img/internal-linking-strategy-2.webp \"A quick map of your pages shows which ones need more links pointing to them.\")",
      "## A 30-minute internal linking tune-up",
      "- List your main service pages. These are your most important pages.",
      "- Make sure each one is linked from your homepage and main menu.",
      "- Open each blog post and add a link to the most relevant service page.",
      "- Add links between closely related services, like furnace repair and furnace installation.",
      "- Find any pages with no links pointing to them and connect them.",
      "## The bottom line",
      "Internal linking costs nothing and pays off twice: visitors find their way to booking you, and Google better understands what you do and which pages matter most. Make it a habit every time you add a page.",
      "Internal linking and on-page SEO are part of our Growth and Authority plans. Related reading: [technical SEO basics](/blog/technical-seo-basics) and [updating old content](/blog/updating-old-content).",
    ],
  },
];
