export default [
  {
    slug: "what-is-ai-seo",
    title: "What Is AI SEO? How to Get Your Business Recommended by ChatGPT",
    metaDescription: "AI SEO helps your business get mentioned when people ask ChatGPT, Gemini or Perplexity for recommendations. Here's how it works and where to start.",
    excerpt: "More people now ask AI tools who to hire before they ever open Google. AI SEO is how you make sure your business is in the answer.",
    category: "AI Search",
    keywords: ["AI SEO", "generative engine optimization", "ChatGPT recommendations", "AI search visibility"],
    content: [
      "Ask ChatGPT for the best accountant in your city, a good dentist near you, or a roofer you can trust, and you'll get an answer. Not a page of ten links, but a short list of names with reasons attached. If your business isn't on that list, that customer may never see you at all.",
      "That shift is why AI SEO exists. Traditional SEO is about ranking in a list of search results. AI SEO, sometimes called generative engine optimization, is about being one of the businesses an AI assistant names when it builds its answer.",
      "## How AI assistants pick who to mention",
      "AI tools like ChatGPT, Gemini and Perplexity pull from what they can find and understand about your business across the web. That includes your website, your Google Business Profile, review sites, directories, news mentions and other pages that talk about you.",
      "They tend to favor businesses whose information is clear, consistent and backed up by more than one source. If your website says one thing, your directory listings say another, and nobody else on the web mentions you, the AI has very little to go on.",
      "## What AI SEO actually involves",
      "The work looks familiar if you know SEO, but the emphasis is different. It starts with making your business easy for machines to understand: structured data (schema) that spells out who you are, what you offer and where you operate, plus consistent business details everywhere you're listed.",
      "From there it's about content that answers real questions directly. AI tools quote pages that give clear, specific answers, so your service pages and articles should say plainly what you do, who it's for, what it costs to get started, and why you're a good choice.",
      "Finally, it means measuring. We run the questions your customers actually ask through the major AI engines and track whether your business shows up, how it's described, and which competitors appear instead.",
      "## Where to start",
      "Search for your own business in ChatGPT, Gemini and Perplexity. Then ask the questions a customer would ask, like 'who's the best [your service] in [your city]?' The answers will tell you quickly whether AI search knows you exist.",
      "If it doesn't, that's not a reason to panic. It's a reason to start now, while most of your competitors still haven't noticed the shift.",
    ],
  },
  {
    slug: "how-ai-assistants-choose-businesses",
    title: "How ChatGPT, Gemini and Perplexity Decide Which Businesses to Recommend",
    metaDescription: "Why do AI assistants recommend some businesses and ignore others? A plain-English look at the signals that get you mentioned in AI answers.",
    excerpt: "AI assistants don't pick businesses at random. Here's what they look at when deciding who to recommend, and what you can control.",
    category: "AI Search",
    keywords: ["AI recommendations", "ChatGPT local business", "Perplexity SEO", "Gemini search"],
    content: [
      "When someone asks an AI assistant for a recommendation, it has to decide which businesses are worth naming. It can't call around or visit your shop, so it relies on what it can read about you online.",
      "Each tool works a little differently, but the businesses that get mentioned tend to share the same traits.",
      "## 1. They're easy to identify",
      "AI tools need to be confident about who you are. Your business name, address, phone number, services and service area should match everywhere: your website, Google Business Profile, Yelp, Facebook and industry directories. Inconsistent details create doubt, and doubt means you get skipped.",
      "## 2. Other sources talk about them",
      "Your own website saying you're great only goes so far. Reviews, local news, partner websites, directories and community pages that mention your business give AI tools independent confirmation that you're real and respected.",
      "## 3. Their content answers questions directly",
      "Assistants build answers from passages that clearly respond to a question. A page that says 'We offer same-day water heater replacement across Vaughan and Richmond Hill, usually within four hours of your call' is far more quotable than one that says 'We pride ourselves on excellence.'",
      "## 4. Their reviews say specific things",
      "Volume and rating matter, but so does what reviewers write. Reviews that mention specific services, locations and outcomes give AI tools the details they need to match you to a specific request.",
      "## 5. Their website is technically readable",
      "If your key content is hidden behind slow scripts, images of text or pages search engines can't crawl, AI tools may never see it. Clean HTML, fast pages and structured data make your information accessible.",
      "## What you can control",
      "You can't control exactly how any AI tool ranks businesses, and anyone who promises guaranteed AI placement is overselling. What you can control is how clear, consistent and well-supported your business information is. That's exactly what AI SEO work focuses on.",
    ],
  },
  {
    slug: "google-ai-overviews-explained",
    title: "Google AI Overviews: What They Mean for Your Website Traffic",
    metaDescription: "Google's AI Overviews answer questions above the search results. Here's what that means for small business traffic and how to stay visible.",
    excerpt: "Google now answers many searches with an AI summary at the top of the page. Here's how that changes the game for business websites.",
    category: "AI Search",
    keywords: ["Google AI Overviews", "AI search traffic", "SEO 2026", "zero-click search"],
    content: [
      "For many searches, the first thing people see on Google is no longer a list of websites. It's an AI Overview: a short generated answer, often with a few linked sources underneath.",
      "For businesses, that raises an obvious question. If Google answers the question itself, does anyone still click through to your website?",
      "## Some clicks are going away",
      "Simple informational searches, like definitions or quick how-to questions, can now be answered without a click. If your traffic strategy relies on that kind of content alone, you may notice fewer visits over time.",
      "## Buying searches still lead to businesses",
      "When someone is ready to hire or buy, they still need a business. Searches like 'emergency plumber near me' or 'best family lawyer in Austin' lead people to Google Maps, business profiles and websites, and AI Overviews often name or link to the businesses they draw from.",
      "## How to get cited in AI Overviews",
      "AI Overviews pull from pages Google already trusts and can understand. The same fundamentals apply: strong technical SEO, clear and specific answers on your pages, structured data, and a solid reputation reflected in reviews and mentions elsewhere.",
      "It also helps to write the way people ask. If customers search 'how much does a kitchen remodel cost,' a page with a direct, honest answer near the top has a much better chance of being used than one that buries it under marketing copy.",
      "## Measure what matters",
      "Traffic alone is becoming a less reliable scorecard. Track calls, form submissions, booked appointments and where those leads came from. A business can get fewer total visits and still win more customers if the right people are finding it.",
      "AI Overviews aren't the end of SEO. They're a reason to do it properly.",
    ],
  },
  {
    slug: "schema-markup-explained",
    title: "Schema Markup Explained: The Code That Helps Google and AI Understand Your Business",
    metaDescription: "Schema markup tells search engines and AI tools exactly who you are and what you offer. Here's what it is and which types your business needs.",
    excerpt: "Schema markup is invisible to visitors but tells search engines and AI exactly what your business does. Here's why it matters.",
    category: "AI Search",
    keywords: ["schema markup", "structured data", "local business schema", "AI search optimization"],
    content: [
      "Schema markup is a small piece of code on your website that describes your business in a format machines can read without guessing. Visitors never see it, but search engines and AI tools rely on it.",
      "Without schema, Google has to infer that '555-0142' is your phone number and 'Mon–Fri 8–6' are your hours. With schema, you state it outright.",
      "## Why it matters more now",
      "Search engines have used structured data for years to power rich results like star ratings and FAQs. AI tools add another reason to care: the clearer your information is, the easier it is for them to describe your business accurately and confidently.",
      "## The schema types most businesses need",
      "LocalBusiness (or a more specific type such as Dentist, Plumber or LegalService) covers your name, address, phone, hours and service area. Organization connects your brand to your logo and social profiles. Service describes what you offer. FAQPage marks up common questions and answers. Article or BlogPosting describes your blog content.",
      "## Common mistakes",
      "The biggest one is markup that doesn't match the page. If your schema lists services or reviews that visitors can't see, search engines may ignore it or treat it as spam. Others include outdated hours, missing service areas, and plugins that add generic markup nobody ever reviewed.",
      "## How to check yours",
      "Google's Rich Results Test and the Schema.org validator will show what structured data is on any page. If you see nothing, or only a bare website name, you have an easy improvement waiting.",
      "Schema won't rescue a weak website on its own, but on a site with good content it's one of the highest-value technical fixes you can make.",
    ],
  },
  {
    slug: "what-is-llms-txt",
    title: "What Is llms.txt and Does Your Website Need One?",
    metaDescription: "llms.txt is a simple file that gives AI tools a clean summary of your website. Here's what it is, what it isn't, and whether it's worth adding.",
    excerpt: "A new file called llms.txt is showing up on websites. Here's what it does and whether your business should bother with it.",
    category: "AI Search",
    keywords: ["llms.txt", "AI crawlers", "AI SEO", "website files"],
    content: [
      "You may have heard of robots.txt, the file that tells search engine crawlers what they can and can't access. llms.txt is a newer idea: a plain-text file that gives AI tools a clean, organized summary of your website.",
      "## What goes in it",
      "An llms.txt file usually includes a short description of your business followed by links to your most important pages, each with a one-line summary. Think of it as a table of contents written for machines.",
      "## What it doesn't do",
      "It isn't a ranking switch. There's no guarantee every AI tool reads it, and it won't make up for a website with thin content or inconsistent business information. It's a proposed standard, and adoption across AI companies is still uneven.",
      "## Why we add it anyway",
      "It takes very little time, it can't hurt, and it forces a useful exercise: deciding which pages actually matter and describing each one in a single clear sentence. If you can't do that, your visitors are probably confused too.",
      "## How to add one",
      "Create a file called llms.txt in the root of your website, so it loads at yourdomain.com/llms.txt. Start with your business name and a short summary, then list your key service pages, pricing, about and contact pages with a short description of each. Keep it accurate and update it when your site changes.",
      "Treat llms.txt as one small part of an AI SEO plan, not the plan itself.",
    ],
  },
  {
    slug: "ai-seo-vs-traditional-seo",
    title: "AI SEO vs Traditional SEO: What's Different and What Still Matters",
    metaDescription: "Do you need AI SEO, traditional SEO, or both? A clear comparison of what each one does and how they work together.",
    excerpt: "AI SEO isn't a replacement for traditional SEO. Here's how the two differ and why the strongest businesses do both.",
    category: "AI Search",
    keywords: ["AI SEO vs SEO", "search engine optimization", "AI search", "SEO strategy"],
    content: [
      "Every few years someone declares SEO dead. The arrival of AI search has brought a new round of it. The reality is less dramatic: the goal is still to be found by people looking for what you sell, but there are now more places they look.",
      "## What traditional SEO does",
      "Traditional SEO helps your pages rank in search results and on Google Maps. It covers technical health, keyword targeting, on-page optimization, local SEO, content and backlinks. It's still where a large share of buying searches start.",
      "## What AI SEO adds",
      "AI SEO focuses on being mentioned inside AI-generated answers in ChatGPT, Gemini, Perplexity and Google's AI Overviews. It puts more weight on clear entity information, structured data, consistent business details across the web, and content that answers questions directly.",
      "## Where they overlap",
      "Most of the foundations are shared. A fast, crawlable website, helpful content, accurate business listings and strong reviews help in both. That's good news: work you do for one usually helps the other.",
      "## Where they differ",
      "Traditional SEO is measured in rankings, clicks and traffic. AI SEO is measured in mentions and citations: whether the AI names you, how it describes you, and who it recommends instead. AI SEO also rewards being discussed on sites other than your own.",
      "## Which one you need",
      "If you rely on search for new customers, you need both, built on one foundation. That's why our Growth and Authority plans include traditional SEO and AI search optimization together rather than treating them as separate projects.",
    ],
  },
  {
    slug: "local-seo-guide",
    title: "Local SEO in 2026: How to Show Up When Customers Search Near You",
    metaDescription: "A practical local SEO guide: Google Business Profile, reviews, citations and location pages that help nearby customers find your business.",
    excerpt: "If you serve customers in a specific area, local SEO decides whether they find you or your competitor. Here's what moves the needle.",
    category: "SEO",
    keywords: ["local SEO", "Google Maps ranking", "near me searches", "local search"],
    content: [
      "When someone searches 'near me' or adds a city name to a search, Google shows a map with a handful of businesses before any regular results. Those spots get a large share of the calls. Local SEO is how you earn one.",
      "## Google weighs three things",
      "Google says local results depend on relevance (how well your profile matches the search), distance (how close you are to the searcher) and prominence (how well known and well reviewed you are). You can't move your building, but you can improve the other two.",
      "## Start with your Google Business Profile",
      "Choose the most accurate primary category, add every relevant secondary category, list your services, set your service area, keep your hours current, and upload real photos. Post updates regularly. An incomplete profile is one of the most common reasons good businesses don't show up.",
      "## Get reviews steadily",
      "A steady stream of recent reviews beats a burst of them two years ago. Ask every happy customer, make it easy with a direct link, and reply to every review, good or bad.",
      "## Keep your details consistent",
      "Your name, address and phone number should match across your website, Google, Apple Maps, Bing, Yelp, Facebook and the directories in your industry. Inconsistent listings make search engines less confident about you.",
      "## Build pages for the areas you serve",
      "If you serve several cities or neighborhoods, a well-written page for each, with real details about the work you do there, helps you show up beyond your immediate location. Avoid copy-and-paste pages with only the city name swapped; they rarely work.",
      "Local SEO isn't one task. It's a set of habits, and the businesses that keep at them month after month are the ones that stay on the map.",
    ],
  },
  {
    slug: "google-business-profile-optimization",
    title: "How to Optimize Your Google Business Profile, Step by Step",
    metaDescription: "A step-by-step checklist to optimize your Google Business Profile so you show up on Google Maps and turn more searchers into calls.",
    excerpt: "Your Google Business Profile is often the first thing customers see. This checklist covers what to fill in and what to keep up.",
    category: "SEO",
    keywords: ["Google Business Profile", "Google Maps", "local SEO checklist", "GBP optimization"],
    content: [
      "For a lot of local searches, your Google Business Profile gets more views than your website. Many people call straight from it without ever visiting your site. That makes it one of the most valuable free marketing tools you have.",
      "## Step 1: Claim and verify it",
      "Search for your business on Google. If you see a profile with a 'claim this business' link, claim it. If you don't see one, create it at business.google.com and complete verification.",
      "## Step 2: Get the categories right",
      "Your primary category has a big influence on which searches you appear for. Pick the most specific one that describes your core business, then add secondary categories for the other services you genuinely offer.",
      "## Step 3: Fill in everything",
      "Add your services with short descriptions, your service area, hours (including holiday hours), phone number, website link, booking link and a description that explains what you do and who you serve in plain language.",
      "## Step 4: Add real photos",
      "Upload photos of your team, your work, your storefront or vehicles, and your finished projects. Real photos build trust far better than stock images. Add new ones regularly.",
      "## Step 5: Ask for reviews and reply to them",
      "Use the review link Google gives you and send it to every happy customer. Reply to every review with a short, genuine response. Replies show both customers and Google that you're active.",
      "## Step 6: Post updates",
      "Google lets you publish posts for offers, news and events. Regular posts keep your profile fresh and give searchers another reason to choose you.",
      "## Step 7: Keep it accurate",
      "Check your profile monthly. Anyone can suggest edits to it, and wrong hours or a changed phone number can quietly cost you calls.",
    ],
  },
  {
    slug: "technical-seo-basics",
    title: "Technical SEO for Business Owners: The 7 Things That Actually Matter",
    metaDescription: "Technical SEO without the jargon. The seven technical issues that most often stop business websites from ranking, and how to spot them.",
    excerpt: "You don't need to be a developer to understand technical SEO. These are the seven issues that matter most for business websites.",
    category: "SEO",
    keywords: ["technical SEO", "site speed", "indexing", "Core Web Vitals"],
    content: [
      "Technical SEO is everything that helps search engines find, load and understand your website. If it's broken, great content won't rank. Here are the seven areas we check first on every new site.",
      "## 1. Can Google find your pages?",
      "Your important pages should be in Google's index. Search 'site:yourdomain.com' to see roughly what Google has, and check Google Search Console for pages it found but chose not to index.",
      "## 2. Is anything blocking crawlers?",
      "A stray 'noindex' tag or a robots.txt rule left over from development can hide an entire website. It happens more often than you'd think, especially after a redesign.",
      "## 3. Do you have a sitemap?",
      "An XML sitemap lists your pages for search engines. Most platforms can create one automatically; make sure it exists and is submitted in Search Console.",
      "## 4. How fast does it load on a phone?",
      "Most local searches happen on mobile. Large images, heavy themes and too many plugins slow pages down. Google's PageSpeed Insights will show you where the time goes.",
      "## 5. Does it work on mobile?",
      "Buttons should be easy to tap, text readable without zooming, and nothing should spill off the side of the screen.",
      "## 6. Are there broken links and redirect chains?",
      "Broken links waste visitors' time and crawlers' attention. After a redesign, old URLs should redirect to the matching new page, not to the home page.",
      "## 7. Is it secure and consistent?",
      "Your site should load on HTTPS, and only one version of it should be live. 'www' and non-'www', and HTTP and HTTPS, should all redirect to the same place.",
      "Fixing these doesn't guarantee rankings, but leaving them broken almost guarantees you won't get them.",
    ],
  },
  {
    slug: "keyword-research-for-small-business",
    title: "Keyword Research for Small Businesses: Find the Searches That Bring Buyers",
    metaDescription: "How to find the keywords that bring paying customers, not just traffic. A practical keyword research process for small businesses.",
    excerpt: "Not every search is worth chasing. Here's how to find the keywords that bring people who are ready to buy.",
    category: "SEO",
    keywords: ["keyword research", "buyer intent keywords", "small business SEO", "SEO strategy"],
    content: [
      "A keyword with huge search volume looks exciting until you realize the people searching it are students, researchers or other businesses. For most small businesses, the best keywords are smaller, more specific, and full of buying intent.",
      "## Start with how customers talk",
      "Write down the questions customers ask on the phone and the words they use to describe their problem. They rarely use your industry's terms. A customer searches 'AC blowing warm air,' not 'refrigerant charge diagnostics.'",
      "## Sort by intent",
      "Group your list into three buckets. Buying searches: '[service] near me,' '[service] in [city],' 'best [service] [city].' Comparing searches: '[service] cost,' '[option A] vs [option B].' Learning searches: 'how to,' 'why does,' 'what is.' Buying searches get your service pages, comparing searches make great articles, and learning searches build authority over time.",
      "## Check what already ranks",
      "Search each important keyword yourself. If the results are all national directories, you'll need a different angle. If they're local businesses with thin pages, you have a real opportunity.",
      "## Map one main topic to each page",
      "Each page should have one clear job. Trying to rank one page for ten different services usually means it ranks for none of them.",
      "## Revisit every few months",
      "Search Console shows which searches already bring you impressions. Those are often your fastest wins: you're close, and a better page can push you up.",
      "Good keyword research isn't a spreadsheet you make once. It's how you decide what to build next.",
    ],
  },
  {
    slug: "how-long-does-seo-take",
    title: "How Long Does SEO Take? An Honest Timeline",
    metaDescription: "How long until SEO works? An honest look at what usually happens in the first month, first quarter and first year of an SEO program.",
    excerpt: "SEO isn't instant, and anyone who promises page one next week is guessing. Here's what a realistic timeline looks like.",
    category: "SEO",
    keywords: ["how long does SEO take", "SEO timeline", "SEO results", "SEO expectations"],
    content: [
      "It's the first question almost every business asks, and the honest answer is: it depends. It depends on your website's starting point, your competition, your location and how consistently the work gets done. But there is a typical pattern.",
      "## Month one: fixing the foundation",
      "The first month is usually spent on an audit and technical fixes, setting up tracking, cleaning up your Google Business Profile and building a keyword plan. You may see small improvements, especially if there were serious technical problems.",
      "## Months two to three: early movement",
      "As new and improved pages get indexed, you'll often see more impressions in Search Console and movement on less competitive keywords. Local map rankings can respond relatively quickly once your profile and reviews improve.",
      "## Months four to six: real momentum",
      "This is typically when results become noticeable in leads, not just reports. Content has had time to be indexed and gain authority, and competitive terms start to move.",
      "## Six months and beyond: compounding",
      "SEO builds on itself. Each useful page adds to your site's authority, and rankings you earn tend to hold far longer than paid ads that stop the day you stop paying.",
      "## What speeds it up",
      "A fast, technically sound site, a clear focus on a few high-value services, consistent publishing, steady reviews, and acting quickly on what the data shows.",
      "## What slows it down",
      "Changing direction every month, thin or duplicated pages, a penalty or messy history on the domain, and very competitive markets.",
      "Be wary of guarantees. What a good SEO partner can promise is clear reporting, so you can see the trend for yourself every month.",
    ],
  },
  {
    slug: "internal-linking-strategy",
    title: "Internal Linking: The Free SEO Win Most Websites Ignore",
    metaDescription: "Internal links help visitors and search engines understand your site. Here's a simple internal linking strategy any business can follow.",
    excerpt: "Linking your own pages together is one of the easiest SEO improvements there is, and most websites barely do it.",
    category: "SEO",
    keywords: ["internal linking", "on-page SEO", "site structure", "SEO tips"],
    content: [
      "Internal links are links from one page on your website to another. They're easy to overlook, but they do two important jobs: they help visitors find what they need, and they show search engines which pages matter most and how your topics connect.",
      "## Why they matter for SEO",
      "Search engines discover pages by following links. A page with no internal links pointing to it is hard to find and looks unimportant. Linking related pages together also helps search engines understand what each page is about.",
      "## A simple structure that works",
      "Your homepage links to your main service pages. Each service page links to related services and to the articles that support it. Each article links back to the relevant service page. That creates clear paths from general to specific and back again.",
      "## Use descriptive link text",
      "'Click here' tells nobody anything. 'Our emergency roof repair service' tells both visitors and search engines exactly what's on the other side of the link.",
      "## Link from your strongest pages",
      "Pages that already get traffic or have links from other websites pass some of that strength through their internal links. Linking from them to pages you want to rank is one of the quickest ways to give those pages a boost.",
      "## Fix orphan pages",
      "Look for pages that nothing links to, especially older blog posts and service pages added later. Each one should be linked from at least one relevant page.",
      "Internal linking costs nothing but a little time, which is exactly why it's worth doing properly.",
    ],
  },
];
