export default [
  {
    slug: "what-is-ai-seo",
    title: "What Is AI SEO? How to Get Your Business Recommended by ChatGPT, Gemini and Google",
    metaDescription: "More homeowners now ask AI assistants who to hire. AI SEO is how you make sure your business is in the answer. What it is, how it works and what you can do today.",
    excerpt: "More people now ask ChatGPT, Gemini or Google's AI who to hire before they ever scroll through search results. AI SEO is how you make sure your business is in the answer.",
    category: "AI Search",
    keywords: ["AI SEO", "generative engine optimization", "ChatGPT recommendations", "AI search visibility"],
    content: [
      "A homeowner in Richmond Hill notices water stains on the ceiling. A few years ago, she would have typed 'roofer near me' into Google and scrolled through results. Today, she might open ChatGPT and ask, 'Who's a reliable roofer in Richmond Hill for a leak repair?' Or she searches Google and reads the AI Overview at the top before looking at anything else.",
      "Either way, the AI gives her a short answer that names a few businesses. If yours isn't one of them, you may never get the chance to compete. AI SEO is the work of making sure you are.",
      "## What AI SEO actually means",
      "AI SEO, sometimes called generative engine optimization (GEO), is the practice of making your business easy for AI assistants to find, understand, trust and recommend. That includes ChatGPT, Google Gemini, Google's AI Overviews and AI Mode, Microsoft Copilot and Perplexity.",
      "It builds on traditional SEO rather than replacing it. Many AI tools pull from search indexes, map data, review sites and directories to form their answers, so solid SEO basics are still the foundation. What changes is the emphasis: AI tools reward businesses whose information is consistent everywhere, whose content answers questions directly, and who are clearly vouched for by other sources. We compare the two in detail in [AI SEO vs traditional SEO](/blog/ai-seo-vs-traditional-seo).",
      "![A homeowner in a kitchen asking an AI assistant on her phone to recommend a local roofer](/blog/img/what-is-ai-seo-1.webp \"More homeowners now ask an AI assistant who to hire before they search.\")",
      "## How AI assistants decide who to recommend",
      "No AI company publishes its exact recipe, and each tool works a little differently. But the businesses that get mentioned tend to share a few traits:",
      "- **They're easy to identify.** The business name, address, phone, services and service area match across the website, Google Business Profile and directories.",
      "- **Other sources talk about them.** Reviews, local news, associations, suppliers and community sites confirm the business is real and respected.",
      "- **Their content answers real questions.** Clear, specific pages are easy for AI to quote.",
      "- **Their reviews mention specifics.** Reviews that name the service, the city and the result help AI match a business to a request.",
      "- **Their website is technically readable.** Fast pages, clean HTML and structured data make the information easy to process.",
      "We go deeper on this in [how AI assistants choose which businesses to recommend](/blog/how-ai-assistants-choose-businesses).",
      "## What AI SEO work includes",
      "### 1. Make your business information consistent everywhere",
      "Start with your Google Business Profile, then make sure the same name, phone, website and service area appear on Bing Places, Apple Business Connect, Yelp and the directories that matter in your trade. For GTA home services, that often includes HomeStars and Houzz. Microsoft's Bing data feeds several AI tools, and Apple's data powers Siri and Apple Maps, so these listings matter more than many businesses realize. Our [Google Business Profile guide](/blog/google-business-profile-optimization) is a good place to start.",
      "### 2. Write content that answers questions directly",
      "AI assistants build answers from passages that clearly respond to a question. A sentence like 'We repair and replace asphalt shingle roofs across Richmond Hill, Vaughan and Aurora, and most leak repairs are done within two days of the inspection' is far more useful to an AI than 'We pride ourselves on quality craftsmanship.'",
      "Give each service its own page. Answer the questions customers ask on every estimate. Add a short FAQ section to key pages, written in plain language.",
      "### 3. Add structured data",
      "Structured data, or schema markup, is code that labels your information for machines: this is a local business, these are its services, this is its service area, these are frequently asked questions. It removes guesswork for both search engines and AI tools. See [schema markup explained](/blog/schema-markup-explained).",
      "### 4. Let AI crawlers read your site",
      "Some websites accidentally block the crawlers AI tools use to find content. Check that your robots.txt file isn't blocking search crawlers such as Googlebot, Bingbot, OAI-SearchBot (used for ChatGPT search) or PerplexityBot. Some sites also publish an llms.txt file, a newer and still-evolving convention for summarizing a site for AI tools. Read more in [what is llms.txt](/blog/what-is-llms-txt).",
      "### 5. Earn reviews and mentions",
      "Reviews are some of the strongest evidence an AI can find, especially detailed ones. Beyond reviews, look for real-world mentions: membership in a trade association such as HRAI for HVAC contractors, RenoMark for renovators, your local chamber of commerce, manufacturer dealer listings, sponsorships, and local news coverage. Each one is another independent source saying you exist and do good work. See [why Google reviews matter in the age of AI search](/blog/google-reviews-and-ai-search).",
      "## How to measure AI visibility",
      "Unlike classic search rankings, there's no single position to track. The practical approach is to regularly ask the main assistants the questions your customers ask, such as 'best furnace repair in Vaughan' or 'who installs heat pumps in Markham', and record whether you're mentioned, how you're described, and which sources are cited. Over time, you can see whether your visibility is improving and which competitors keep showing up.",
      "![A business owner reviewing a report of AI search mentions on a laptop in a small office](/blog/img/what-is-ai-seo-2.webp \"Track where you're mentioned across AI assistants, and which competitors show up instead.\")",
      "## What AI SEO can't do",
      "Be wary of anyone who guarantees you'll be the top recommendation in ChatGPT. Nobody controls how these tools rank businesses, and their answers vary from person to person and day to day. What you can control is how clear, consistent and well supported your business information is. That consistently improves your odds.",
      "It also takes time. AI tools update their understanding of a business gradually as new reviews, mentions and content appear. Expect steady progress over months, not overnight results.",
      "## Where to start",
      "If you do only three things this month, make them these:",
      "- Fully complete and verify your Google Business Profile, Bing Places and Apple Business Connect listings with identical details.",
      "- Make sure your website has a clear page for each main service that answers common questions directly.",
      "- Start asking every customer for a Google review.",
      "## The bottom line",
      "AI assistants are quickly becoming the first place homeowners go for recommendations. The businesses they name are the ones that are easy to understand, consistent everywhere, and clearly trusted by others. That's what AI SEO builds.",
      "AI search optimization is included in our Growth and Authority plans, and we track where you're mentioned every month. Curious where you stand today? [Request a free AI visibility audit](/contact?interest=audit).",
    ],
  },
  {
    slug: "how-ai-assistants-choose-businesses",
    title: "How ChatGPT, Gemini and Perplexity Decide Which Businesses to Recommend",
    metaDescription: "Why do AI assistants recommend some businesses and ignore others? A plain-English look at the signals that get you mentioned in AI answers.",
    excerpt: "AI assistants don't pick businesses at random. Here's what they look at when deciding who to recommend, and what you can control.",
    category: "AI Search",
    keywords: ["AI recommendations", "ChatGPT local business", "Perplexity SEO", "Gemini search"],
    content: [
      "When someone asks an AI assistant for a recommendation, it has to decide which businesses are worth naming. It can't call around or visit your shop, so it relies on what it can read about you online.",
      "Each tool works a little differently, but the businesses that get mentioned tend to share the same traits.",
      "## 1. They're easy to identify",
      "AI tools need to be confident about who you are. Your business name, address, phone number, services and service area should match everywhere: your website, Google Business Profile, Yelp, Facebook and industry directories. Inconsistent details create doubt, and doubt means you get skipped.",
      "## 2. Other sources talk about them",
      "Your own website saying you're great only goes so far. Reviews, local news, partner websites, directories and community pages that mention your business give AI tools independent confirmation that you're real and respected.",
      "## 3. Their content answers questions directly",
      "Assistants build answers from passages that clearly respond to a question. A page that says 'We offer same-day water heater replacement across Vaughan and Richmond Hill, usually within four hours of your call' is far more quotable than one that says 'We pride ourselves on excellence.'",
      "## 4. Their reviews say specific things",
      "Volume and rating matter, but so does what reviewers write. Reviews that mention specific services, locations and outcomes give AI tools the details they need to match you to a specific request.",
      "## 5. Their website is technically readable",
      "If your key content is hidden behind slow scripts, images of text or pages search engines can't crawl, AI tools may never see it. Clean HTML, fast pages and structured data make your information accessible.",
      "## What you can control",
      "You can't control exactly how any AI tool ranks businesses, and anyone who promises guaranteed AI placement is overselling. What you can control is how clear, consistent and well-supported your business information is. That's exactly what AI SEO work focuses on.",
    ],
  },
  {
    slug: "google-ai-overviews-explained",
    title: "Google AI Overviews: What They Mean for Your Website Traffic",
    metaDescription: "Google's AI Overviews answer questions above the search results. Here's what that means for small business traffic and how to stay visible.",
    excerpt: "Google now answers many searches with an AI summary at the top of the page. Here's how that changes the game for business websites.",
    category: "AI Search",
    keywords: ["Google AI Overviews", "AI search traffic", "SEO 2026", "zero-click search"],
    content: [
      "For many searches, the first thing people see on Google is no longer a list of websites. It's an AI Overview: a short generated answer, often with a few linked sources underneath.",
      "For businesses, that raises an obvious question. If Google answers the question itself, does anyone still click through to your website?",
      "## Some clicks are going away",
      "Simple informational searches, like definitions or quick how-to questions, can now be answered without a click. If your traffic strategy relies on that kind of content alone, you may notice fewer visits over time.",
      "## Buying searches still lead to businesses",
      "When someone is ready to hire or buy, they still need a business. Searches like 'emergency plumber near me' or 'best family lawyer in Austin' lead people to Google Maps, business profiles and websites, and AI Overviews often name or link to the businesses they draw from.",
      "## How to get cited in AI Overviews",
      "AI Overviews pull from pages Google already trusts and can understand. The same fundamentals apply: strong technical SEO, clear and specific answers on your pages, structured data, and a solid reputation reflected in reviews and mentions elsewhere.",
      "It also helps to write the way people ask. If customers search 'how much does a kitchen remodel cost,' a page with a direct, honest answer near the top has a much better chance of being used than one that buries it under marketing copy.",
      "## Measure what matters",
      "Traffic alone is becoming a less reliable scorecard. Track calls, form submissions, booked appointments and where those leads came from. A business can get fewer total visits and still win more customers if the right people are finding it.",
      "AI Overviews aren't the end of SEO. They're a reason to do it properly.",
    ],
  },
  {
    slug: "schema-markup-explained",
    title: "Schema Markup Explained: The Code That Helps Google and AI Understand Your Business",
    metaDescription: "Schema markup tells search engines and AI tools exactly who you are and what you offer. Here's what it is and which types your business needs.",
    excerpt: "Schema markup is invisible to visitors but tells search engines and AI exactly what your business does. Here's why it matters.",
    category: "AI Search",
    keywords: ["schema markup", "structured data", "local business schema", "AI search optimization"],
    content: [
      "Schema markup is a small piece of code on your website that describes your business in a format machines can read without guessing. Visitors never see it, but search engines and AI tools rely on it.",
      "Without schema, Google has to infer that '555-0142' is your phone number and 'Mon–Fri 8–6' are your hours. With schema, you state it outright.",
      "## Why it matters more now",
      "Search engines have used structured data for years to power rich results like star ratings and FAQs. AI tools add another reason to care: the clearer your information is, the easier it is for them to describe your business accurately and confidently.",
      "## The schema types most businesses need",
      "LocalBusiness (or a more specific type such as Dentist, Plumber or LegalService) covers your name, address, phone, hours and service area. Organization connects your brand to your logo and social profiles. Service describes what you offer. FAQPage marks up common questions and answers. Article or BlogPosting describes your blog content.",
      "## Common mistakes",
      "The biggest one is markup that doesn't match the page. If your schema lists services or reviews that visitors can't see, search engines may ignore it or treat it as spam. Others include outdated hours, missing service areas, and plugins that add generic markup nobody ever reviewed.",
      "## How to check yours",
      "Google's Rich Results Test and the Schema.org validator will show what structured data is on any page. If you see nothing, or only a bare website name, you have an easy improvement waiting.",
      "Schema won't rescue a weak website on its own, but on a site with good content it's one of the highest-value technical fixes you can make.",
    ],
  },
  {
    slug: "what-is-llms-txt",
    title: "What Is llms.txt and Does Your Website Need One?",
    metaDescription: "llms.txt is a simple file that gives AI tools a clean summary of your website. Here's what it is, what it isn't, and whether it's worth adding.",
    excerpt: "A new file called llms.txt is showing up on websites. Here's what it does and whether your business should bother with it.",
    category: "AI Search",
    keywords: ["llms.txt", "AI crawlers", "AI SEO", "website files"],
    content: [
      "You may have heard of robots.txt, the file that tells search engine crawlers what they can and can't access. llms.txt is a newer idea: a plain-text file that gives AI tools a clean, organized summary of your website.",
      "## What goes in it",
      "An llms.txt file usually includes a short description of your business followed by links to your most important pages, each with a one-line summary. Think of it as a table of contents written for machines.",
      "## What it doesn't do",
      "It isn't a ranking switch. There's no guarantee every AI tool reads it, and it won't make up for a website with thin content or inconsistent business information. It's a proposed standard, and adoption across AI companies is still uneven.",
      "## Why we add it anyway",
      "It takes very little time, it can't hurt, and it forces a useful exercise: deciding which pages actually matter and describing each one in a single clear sentence. If you can't do that, your visitors are probably confused too.",
      "## How to add one",
      "Create a file called llms.txt in the root of your website, so it loads at yourdomain.com/llms.txt. Start with your business name and a short summary, then list your key service pages, pricing, about and contact pages with a short description of each. Keep it accurate and update it when your site changes.",
      "Treat llms.txt as one small part of an AI SEO plan, not the plan itself.",
    ],
  },
  {
    slug: "ai-seo-vs-traditional-seo",
    title: "AI SEO vs Traditional SEO: What's Different and What Still Matters",
    metaDescription: "Do you need AI SEO, traditional SEO, or both? A clear comparison of what each one does and how they work together.",
    excerpt: "AI SEO isn't a replacement for traditional SEO. Here's how the two differ and why the strongest businesses do both.",
    category: "AI Search",
    keywords: ["AI SEO vs SEO", "search engine optimization", "AI search", "SEO strategy"],
    content: [
      "Every few years someone declares SEO dead. The arrival of AI search has brought a new round of it. The reality is less dramatic: the goal is still to be found by people looking for what you sell, but there are now more places they look.",
      "## What traditional SEO does",
      "Traditional SEO helps your pages rank in search results and on Google Maps. It covers technical health, keyword targeting, on-page optimization, local SEO, content and backlinks. It's still where a large share of buying searches start.",
      "## What AI SEO adds",
      "AI SEO focuses on being mentioned inside AI-generated answers in ChatGPT, Gemini, Perplexity and Google's AI Overviews. It puts more weight on clear entity information, structured data, consistent business details across the web, and content that answers questions directly.",
      "## Where they overlap",
      "Most of the foundations are shared. A fast, crawlable website, helpful content, accurate business listings and strong reviews help in both. That's good news: work you do for one usually helps the other.",
      "## Where they differ",
      "Traditional SEO is measured in rankings, clicks and traffic. AI SEO is measured in mentions and citations: whether the AI names you, how it describes you, and who it recommends instead. AI SEO also rewards being discussed on sites other than your own.",
      "## Which one you need",
      "If you rely on search for new customers, you need both, built on one foundation. That's why our Growth and Authority plans include traditional SEO and AI search optimization together rather than treating them as separate projects.",
    ],
  },
  {
    slug: "local-seo-guide",
    title: "Local SEO in 2026: How GTA Contractors Show Up When Customers Search Near Them",
    metaDescription: "A practical local SEO guide for GTA contractors: how Google decides who shows up on Maps, what to fix first, and how to grow calls from local search without gimmicks.",
    excerpt: "When a homeowner searches for a contractor near them, Google shows a handful of businesses on a map. Here's how to become one of them.",
    category: "SEO",
    keywords: ["local SEO", "Google Maps ranking", "contractor SEO", "near me searches"],
    content: [
      "When a homeowner in Etobicoke searches 'electrician near me', Google shows a map with three businesses underneath, then a list of regular results, and often some ads above both. Most of the calls go to the businesses in that map section. Local SEO is the work of earning a place there, and in the regular results below it.",
      "This guide covers what actually moves the needle for contractors in the GTA, in the order we'd tackle it.",
      "## How Google decides who shows up locally",
      "Google is unusually open about this. Local results are based mainly on three factors:",
      "- **Relevance:** how well your business matches what was searched. If someone searches 'heat pump installation', a business that clearly lists heat pump installation is more relevant than one that just says 'HVAC'.",
      "- **Distance:** how far your business is from the searcher or the location in their search. You can't change where you're based, but you can make your service area clear.",
      "- **Prominence:** how well known and well regarded your business is, based on things like reviews, links, mentions across the web and your overall search presence.",
      "Everything in local SEO works on one or more of these three.",
      "![A smartphone showing a Google Maps search with business pins spread across a suburban neighbourhood](/blog/img/local-seo-guide-1.webp \"Most local calls start from the map results, so that's where to focus first.\")",
      "## Step 1: Get your Google Business Profile right",
      "Your Business Profile is the single most important local SEO asset you have. It's what appears in the map results. Make sure it's verified, uses your real business name, has the most specific primary category, lists every service, shows your service areas, and is full of real photos. We walk through every setting in our [Google Business Profile guide](/blog/google-business-profile-optimization).",
      "## Step 2: Build a page for each service",
      "Google needs to see that you're relevant for each service you want to be found for. A single 'Services' page with a list won't do it. Give each main service its own page that explains what's involved, the problems it solves, rough timelines, what affects the price, and the questions customers ask. Link to these pages from your Business Profile and your homepage.",
      "## Step 3: Show your service area honestly",
      "Most contractors are service-area businesses: you go to customers rather than customers coming to you. Make your service area clear on your website and your Business Profile.",
      "If you want pages for specific cities, make each one genuinely useful: jobs you've completed there, local housing considerations (older homes in the Junction, newer subdivisions in Brampton), and reviews from customers in that area. Creating dozens of near-identical pages that only swap the city name is what Google calls doorway pages, which are against its spam policies and can hurt you.",
      "## Step 4: Make your business details consistent everywhere",
      "Your business name, phone number, website and address (if you show one) should match exactly across your website, Google, Bing Places, Apple Business Connect, Yelp, YellowPages.ca, the Better Business Bureau, and home-service directories like HomeStars and Houzz. Inconsistent details, such as an old phone number or a former address, create doubt for search engines and AI tools alike.",
      "## Step 5: Earn reviews, constantly",
      "Reviews feed directly into prominence, and Google says review count and rating factor into local ranking. They also decide who gets the call once someone sees the map. The key is consistency: ask every customer, right after the job, with a direct link. Our post on [Google reviews and AI search](/blog/google-reviews-and-ai-search) covers how to do it within Google's rules.",
      "## Step 6: Earn local links and mentions",
      "Links from other reputable local websites tell Google you're a real, established part of the community. For contractors, good sources include:",
      "- Manufacturer and supplier dealer locators, such as an HVAC brand's dealer finder.",
      "- Trade associations and certification programs.",
      "- Your local chamber of commerce or BIA.",
      "- Sponsorships of youth sports teams, charity events and community festivals.",
      "- Local news coverage of a notable project or community involvement.",
      "A handful of genuine local links is worth far more than hundreds of low-quality ones bought online.",
      "## Step 7: Cover the technical basics",
      "Your website should load quickly on phones, use HTTPS, have a clear page title and description on every page, and include local business structured data. None of this is glamorous, but problems here can quietly hold everything else back. See [technical SEO basics](/blog/technical-seo-basics).",
      "## What about ads?",
      "Google Ads and Local Services Ads can put you at the top of the page right away, while SEO builds over time. Many contractors use both: ads for immediate leads, SEO for long-term, lower-cost visibility. We compare them in [Google Ads vs SEO](/blog/google-ads-vs-seo).",
      "![A contractor's work truck parked on a residential street in a GTA neighbourhood](/blog/img/local-seo-guide-2.webp \"Local SEO is about being the obvious choice in the neighbourhoods you actually serve.\")",
      "## How to track progress",
      "Rankings for a single keyword bounce around and depend on where the searcher is standing, so don't obsess over one number. Watch the trends that matter:",
      "- Calls, website clicks and direction requests in your Business Profile performance report.",
      "- Search impressions and clicks in Google Search Console.",
      "- Calls and form submissions tracked on your website.",
      "- Most importantly, estimates booked and jobs won from local search.",
      "## How long does it take?",
      "Fixing your Business Profile and reviews can show results within weeks. Content, service pages and local links typically take several months to build momentum, and competitive trades in dense parts of the GTA take longer. We explain realistic timelines in [how long SEO takes](/blog/how-long-does-seo-take).",
      "## The bottom line",
      "Local SEO isn't about tricks. It's about giving Google clear proof that you do the job, in the area, and that customers trust you. Get your Business Profile right, build real service pages, keep your details consistent, and earn reviews and local mentions month after month.",
      "Local SEO is part of our Growth and Authority plans. Want to know where you stand right now? [Request a free audit](/contact?interest=audit) and we'll show you what to fix first.",
    ],
  },
  {
    slug: "google-business-profile-optimization",
    title: "How to Optimize Your Google Business Profile: A Step-by-Step Guide for Contractors",
    metaDescription: "Your Google Business Profile decides whether you show up on Google Maps. A step-by-step guide for contractors: categories, service areas, photos, reviews and the mistakes that get profiles suspended.",
    excerpt: "Your Google Business Profile is often the first thing a homeowner sees. Here's how to set up every part of it properly, step by step.",
    category: "SEO",
    keywords: ["Google Business Profile", "Google Maps", "local SEO checklist", "contractor Google listing"],
    content: [
      "For most contractors, your Google Business Profile does more selling than your website. It's what appears in the map results when someone searches for your trade nearby, and it's often the first and only thing a homeowner looks at before calling. A complete, accurate, active profile gets more calls. A thin or neglected one gets skipped.",
      "Here's how to set up every part of it properly, in order.",
      "## 1. Claim and verify your profile",
      "Search for your business on Google Maps. If a profile already exists, claim it. If not, create one at business.google.com. Google will then ask you to verify that you're the real owner. These days that's often a short video showing your business, such as your branded vehicle, tools, business documents and the area you work in. Follow the instructions exactly, because unverified profiles don't show up properly.",
      "Use a business email you control as the owner, and add your office manager or marketing partner as a manager rather than handing over the owner login.",
      "## 2. Use your real business name",
      "Your profile name must match the name you use in the real world: on your truck, invoices and signage. Adding keywords, like 'Northline Plumbing | Emergency Plumber Vaughan', is against Google's guidelines and is one of the most common reasons profiles get suspended. It may give a short-term bump, but it's not worth the risk.",
      "## 3. Choose the right categories",
      "Your primary category is one of the strongest signals for which searches you appear in. Choose the most specific one that describes your core business, such as 'Plumber', 'HVAC contractor', 'Roofing contractor' or 'Electrician'. Then add secondary categories for other services you genuinely offer, like 'Water heater installation service' or 'Air conditioning repair service'. Don't add categories for work you don't do.",
      "## 4. Set up your service area correctly",
      "Most contractors are service-area businesses: you travel to customers. If customers don't come to your address, Google's guidelines say to hide it and list your service areas instead. You can add up to 20 service areas, such as cities or postal-code areas, and Google recommends keeping them within about two hours' driving distance of your base.",
      "Never use a virtual office, a mailbox store or a relative's house as your address to appear in a city where you don't actually operate. It violates Google's guidelines and is a common cause of suspensions.",
      "![A contractor photographing a newly installed furnace with his phone for his Google Business Profile](/blog/img/google-business-profile-optimization-1.webp \"Real photos of your own work are some of the most persuasive things on your profile.\")",
      "## 5. Add accurate hours, phone and website",
      "List your regular hours and update them for holidays. If you offer emergency service, make it clear in your services and description, but only list 24-hour hours if someone actually answers.",
      "Use your main business phone number, the same one on your website. Link to your homepage or your most relevant page. Adding tracking parameters to that link lets you see in your analytics exactly how many visits come from your profile.",
      "## 6. List every service",
      "Add each service you offer with a short, plain-language description. This helps you show up for specific searches, and homeowners read these lists to check that you do what they need. Be specific: 'Furnace repair', 'Furnace installation', 'Heat pump installation' and 'Duct cleaning' are better than one generic 'Heating services'.",
      "## 7. Write a useful description",
      "You have 750 characters to describe your business. Say what you do, where you work, what makes you different, and how long you've been doing it. Write it for homeowners, not for keywords, and don't include links or promotions.",
      "## 8. Upload real photos regularly",
      "Add your logo and a cover photo, then keep adding real photos: finished jobs, before-and-after shots, your team, your trucks. Photos of actual work build trust in a way stock images can't. Adding a few new ones every month also signals that your business is active.",
      "## 9. Post updates",
      "Google lets you publish short posts on your profile: seasonal tune-up reminders, recent projects, offers or helpful tips. They don't need to be elaborate. Posting regularly keeps your profile fresh and gives homeowners one more reason to choose you.",
      "## 10. Earn and respond to reviews",
      "Reviews are a major factor in both ranking and conversion. Ask every customer, right after the job, with a direct link to your review form. Reply to every review, positive or negative, politely and specifically. Our guide to [Google reviews in the age of AI search](/blog/google-reviews-and-ai-search) covers the right way to ask and the rules to follow.",
      "## 11. Turn on the right contact options",
      "Google discontinued Business Profile chat in 2024, so customers can no longer message you directly through your listing. That makes the other routes more important: a clearly listed phone number backed by [missed call text back](/blog/missed-call-text-back), and a website with [AI chat](/blog/ai-website-chat-vs-contact-forms) and online booking where it fits your business.",
      "## 12. Keep it accurate",
      "Anyone can suggest edits to a public profile, and Google sometimes applies them automatically. Log in regularly to check that your hours, phone number, categories and website are still correct, and review any changes Google suggests.",
      "![A tradesperson checking his Google Business Profile insights on a phone outside a client's home](/blog/img/google-business-profile-optimization-2.webp \"Check your profile regularly to keep details accurate and see how many calls it brings in.\")",
      "## Mistakes that get profiles suspended",
      "A suspended profile disappears from Maps, sometimes for weeks. Avoid these common causes:",
      "- Stuffing keywords or city names into your business name.",
      "- Using a virtual office, mailbox or fake address.",
      "- Creating more than one profile for the same business.",
      "- Buying reviews, reviewing yourself, or offering incentives for reviews.",
      "- Listing services or locations you don't actually cover.",
      "## How to measure results",
      "Your profile's performance report shows how many people called, requested directions, visited your website or found you through searches. Watch those numbers month to month, and connect them to the jobs you actually win.",
      "## The bottom line",
      "Your Google Business Profile is free, and for many contractors it's the most valuable marketing asset they have. Set up every section properly, keep it accurate, keep adding photos and reviews, and stay well within Google's guidelines.",
      "Google Business Profile optimization is included in our Growth and Authority plans. Not sure how yours stacks up? [Request a free audit](/contact?interest=audit) and we'll show you what to fix.",
    ],
  },
  {
    slug: "technical-seo-basics",
    title: "Technical SEO for Business Owners: The 7 Things That Actually Matter",
    metaDescription: "Technical SEO without the jargon. The seven technical issues that most often stop business websites from ranking, and how to spot them.",
    excerpt: "You don't need to be a developer to understand technical SEO. These are the seven issues that matter most for business websites.",
    category: "SEO",
    keywords: ["technical SEO", "site speed", "indexing", "Core Web Vitals"],
    content: [
      "Technical SEO is everything that helps search engines find, load and understand your website. If it's broken, great content won't rank. Here are the seven areas we check first on every new site.",
      "## 1. Can Google find your pages?",
      "Your important pages should be in Google's index. Search 'site:yourdomain.com' to see roughly what Google has, and check Google Search Console for pages it found but chose not to index.",
      "## 2. Is anything blocking crawlers?",
      "A stray 'noindex' tag or a robots.txt rule left over from development can hide an entire website. It happens more often than you'd think, especially after a redesign.",
      "## 3. Do you have a sitemap?",
      "An XML sitemap lists your pages for search engines. Most platforms can create one automatically; make sure it exists and is submitted in Search Console.",
      "## 4. How fast does it load on a phone?",
      "Most local searches happen on mobile. Large images, heavy themes and too many plugins slow pages down. Google's PageSpeed Insights will show you where the time goes.",
      "## 5. Does it work on mobile?",
      "Buttons should be easy to tap, text readable without zooming, and nothing should spill off the side of the screen.",
      "## 6. Are there broken links and redirect chains?",
      "Broken links waste visitors' time and crawlers' attention. After a redesign, old URLs should redirect to the matching new page, not to the home page.",
      "## 7. Is it secure and consistent?",
      "Your site should load on HTTPS, and only one version of it should be live. 'www' and non-'www', and HTTP and HTTPS, should all redirect to the same place.",
      "Fixing these doesn't guarantee rankings, but leaving them broken almost guarantees you won't get them.",
    ],
  },
  {
    slug: "keyword-research-for-small-business",
    title: "Keyword Research for Small Businesses: Find the Searches That Bring Buyers",
    metaDescription: "How to find the keywords that bring paying customers, not just traffic. A practical keyword research process for small businesses.",
    excerpt: "Not every search is worth chasing. Here's how to find the keywords that bring people who are ready to buy.",
    category: "SEO",
    keywords: ["keyword research", "buyer intent keywords", "small business SEO", "SEO strategy"],
    content: [
      "A keyword with huge search volume looks exciting until you realize the people searching it are students, researchers or other businesses. For most small businesses, the best keywords are smaller, more specific, and full of buying intent.",
      "## Start with how customers talk",
      "Write down the questions customers ask on the phone and the words they use to describe their problem. They rarely use your industry's terms. A customer searches 'AC blowing warm air,' not 'refrigerant charge diagnostics.'",
      "## Sort by intent",
      "Group your list into three buckets. Buying searches: '[service] near me,' '[service] in [city],' 'best [service] [city].' Comparing searches: '[service] cost,' '[option A] vs [option B].' Learning searches: 'how to,' 'why does,' 'what is.' Buying searches get your service pages, comparing searches make great articles, and learning searches build authority over time.",
      "## Check what already ranks",
      "Search each important keyword yourself. If the results are all national directories, you'll need a different angle. If they're local businesses with thin pages, you have a real opportunity.",
      "## Map one main topic to each page",
      "Each page should have one clear job. Trying to rank one page for ten different services usually means it ranks for none of them.",
      "## Revisit every few months",
      "Search Console shows which searches already bring you impressions. Those are often your fastest wins: you're close, and a better page can push you up.",
      "Good keyword research isn't a spreadsheet you make once. It's how you decide what to build next.",
    ],
  },
  {
    slug: "how-long-does-seo-take",
    title: "How Long Does SEO Take? An Honest Timeline",
    metaDescription: "How long until SEO works? An honest look at what usually happens in the first month, first quarter and first year of an SEO program.",
    excerpt: "SEO isn't instant, and anyone who promises page one next week is guessing. Here's what a realistic timeline looks like.",
    category: "SEO",
    keywords: ["how long does SEO take", "SEO timeline", "SEO results", "SEO expectations"],
    content: [
      "It's the first question almost every business asks, and the honest answer is: it depends. It depends on your website's starting point, your competition, your location and how consistently the work gets done. But there is a typical pattern.",
      "## Month one: fixing the foundation",
      "The first month is usually spent on an audit and technical fixes, setting up tracking, cleaning up your Google Business Profile and building a keyword plan. You may see small improvements, especially if there were serious technical problems.",
      "## Months two to three: early movement",
      "As new and improved pages get indexed, you'll often see more impressions in Search Console and movement on less competitive keywords. Local map rankings can respond relatively quickly once your profile and reviews improve.",
      "## Months four to six: real momentum",
      "This is typically when results become noticeable in leads, not just reports. Content has had time to be indexed and gain authority, and competitive terms start to move.",
      "## Six months and beyond: compounding",
      "SEO builds on itself. Each useful page adds to your site's authority, and rankings you earn tend to hold far longer than paid ads that stop the day you stop paying.",
      "## What speeds it up",
      "A fast, technically sound site, a clear focus on a few high-value services, consistent publishing, steady reviews, and acting quickly on what the data shows.",
      "## What slows it down",
      "Changing direction every month, thin or duplicated pages, a penalty or messy history on the domain, and very competitive markets.",
      "Be wary of guarantees. What a good SEO partner can promise is clear reporting, so you can see the trend for yourself every month.",
    ],
  },
  {
    slug: "internal-linking-strategy",
    title: "Internal Linking: The Free SEO Win Most Websites Ignore",
    metaDescription: "Internal links help visitors and search engines understand your site. Here's a simple internal linking strategy any business can follow.",
    excerpt: "Linking your own pages together is one of the easiest SEO improvements there is, and most websites barely do it.",
    category: "SEO",
    keywords: ["internal linking", "on-page SEO", "site structure", "SEO tips"],
    content: [
      "Internal links are links from one page on your website to another. They're easy to overlook, but they do two important jobs: they help visitors find what they need, and they show search engines which pages matter most and how your topics connect.",
      "## Why they matter for SEO",
      "Search engines discover pages by following links. A page with no internal links pointing to it is hard to find and looks unimportant. Linking related pages together also helps search engines understand what each page is about.",
      "## A simple structure that works",
      "Your homepage links to your main service pages. Each service page links to related services and to the articles that support it. Each article links back to the relevant service page. That creates clear paths from general to specific and back again.",
      "## Use descriptive link text",
      "'Click here' tells nobody anything. 'Our emergency roof repair service' tells both visitors and search engines exactly what's on the other side of the link.",
      "## Link from your strongest pages",
      "Pages that already get traffic or have links from other websites pass some of that strength through their internal links. Linking from them to pages you want to rank is one of the quickest ways to give those pages a boost.",
      "## Fix orphan pages",
      "Look for pages that nothing links to, especially older blog posts and service pages added later. Each one should be linked from at least one relevant page.",
      "Internal linking costs nothing but a little time, which is exactly why it's worth doing properly.",
    ],
  },
];
